! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

SUBROUTINE CLOUDSC_IN &
 !---input
 & (iu,    KLON,    KLEV,&
 & PTSPHY,&
 & PT, PQ, tendency_cml,tendency_tmp, &
 & PVFA, PVFL, PVFI, PDYNA, PDYNL, PDYNI, &
 & PHRSW,    PHRLW,&
 & PVERVEL,  PAP,      PAPH,&
 & PLSM,     LDCUM,    KTYPE, &
 & PLU,      PLUDE,    PSNDE,    PMFU,     PMFD,&
 & LDSLPHY,  LDMAINCALL, &
 !---prognostic fields
 & PA,&
 & PCLV,  &
 & PSUPSAT, &
!-- arrays for aerosol-cloud interactions
!!! & PQAER,    KAER, &
 & PLCRIT_AER,PICRIT_AER,&
 & PRE_ICE,&
 & PCCN,     PNICE,&
 & PEXTRA,   KFLDX)  

!===============================================================================

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHYDER ,ONLY : STATE_TYPE
!USE YOMHOOK  , ONLY : LHOOK, DR_HOOK
USE YOMMP0   , ONLY : LSCMEC
USE YOMCST   , ONLY : RG, RD, RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV  
USE YOETHF   , ONLY : R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, &
 & R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU, &
 & RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2
USE YOECLDP  , ONLY : YRECLDP, TECLDP, NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV
USE YOMJFH   , ONLY : N_VMASS
USE YOEPHLI  , ONLY : YREPHLI, TEPHLI
USE DIAG_MOD , ONLY : NUMOMP

IMPLICIT NONE

!-------------------------------------------------------------------------------
!                 Declare input/output arguments
!-------------------------------------------------------------------------------

INTEGER(KIND=JPIM), INTENT(in) :: iu
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON             ! Number of grid points
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV             ! Number of levels

REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLCRIT_AER(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PICRIT_AER(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PRE_ICE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PCCN(KLON,KLEV)     ! liquid cloud condensation nuclei
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PNICE(KLON,KLEV)    ! ice number concentration (cf. CCN)

REAL(KIND=JPRB)   ,INTENT(OUT)    :: PTSPHY            ! Physics timestep
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PT(KLON,KLEV)    ! T at start of callpar
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PQ(KLON,KLEV)    ! Q at start of callpar
TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_cml   ! cumulative tendency used for final output
TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_tmp   ! cumulative tendency used as input
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFA(KLON,KLEV)  ! CC from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFL(KLON,KLEV)  ! Liq from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFI(KLON,KLEV)  ! Ice from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNA(KLON,KLEV) ! CC from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNL(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNI(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PHRSW(KLON,KLEV) ! Short-wave heating rate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PHRLW(KLON,KLEV) ! Long-wave heating rate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVERVEL(KLON,KLEV) !Vertical velocity
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PAP(KLON,KLEV)   ! Pressure on full levels
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PAPH(KLON,KLEV+1)! Pressure on half levels
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLSM(KLON)       ! Land fraction (0-1) 
LOGICAL           ,INTENT(OUT)    :: LDCUM(KLON)      ! Convection active
INTEGER(KIND=JPIM),INTENT(OUT)    :: KTYPE(KLON)      ! Convection type 0,1,2
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLU(KLON,KLEV)   ! Conv. condensate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLUDE(KLON,KLEV) ! Conv. detrained water 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PSNDE(KLON,KLEV) ! Conv. detrained snow
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PMFU(KLON,KLEV)  ! Conv. mass flux up
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PMFD(KLON,KLEV)  ! Conv. mass flux down
LOGICAL           ,INTENT(OUT)    :: LDSLPHY 
LOGICAL           ,INTENT(OUT)    :: LDMAINCALL       ! T if main call to cloudsc
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PA(KLON,KLEV)    ! Original Cloud fraction (t)

INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDX 
REAL(KIND=JPRB)   ,INTENT(OUT) :: PEXTRA(KLON,KLEV,KFLDX) ! extra fields

REAL(KIND=JPRB)   ,INTENT(OUT)    :: PCLV(KLON,KLEV,NCLV) 

 ! Supersat clipped at previous time level in SLTEND
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PSUPSAT(KLON,KLEV)

#include "abor1.intfb.h"

REAL(KIND=JPRB) :: ZDUMMY(1)
REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER(KIND=JPIM)  I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV, II(6)

!-- A trick to get more readable TYPE-struct output: copy type data to namelist !
TYPE(TECLDP) :: COPY_YRECLDP
TYPE(TEPHLI) :: COPY_YREPHLI
namelist/NAM_YRECLDP/ COPY_YRECLDP
namelist/NAM_YREPHLI/ COPY_YREPHLI

!-- We need to read LOGICALs in as 4-byte integers & convert them to LOGICALs based
!   whether they were 0 (= FALSE) or not-0 (= TRUE) 
INTEGER(KIND=JPIM) :: I_LDSLPHY, I_LDMAINCALL, I_LDCUM(KLON)

!IF (LHOOK) CALL DR_HOOK('CLOUDSC_IN',0,ZHOOK_HANDLE)

read(iu) PTSPHY
!read(iu) LDSLPHY
!read(iu) LDMAINCALL
read(iu) I_LDSLPHY
LDSLPHY = (I_LDSLPHY /= 0)
read(iu) I_LDMAINCALL
LDMAINCALL = (I_LDMAINCALL /= 0)

1000 format(1x,a,L1)
#ifdef DEBUG_OUT
write(0,1000) 'CLOUDSC_IN: LDSLPHY=',LDSLPHY
write(0,1000) 'CLOUDSC_IN: LDMAINCALL=',LDMAINCALL
#endif

read(iu) LSCMEC
read(iu) RG, RD, RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV  
read(iu) R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, &
 & R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU, &
 & RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2
read(iu) I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV

if ( I_NCLDQV /= NCLDQV .or. &
   & I_NCLDQL /= NCLDQL .or. &
   & I_NCLDQR /= NCLDQR .or. &
   & I_NCLDQI /= NCLDQI .or. &
   & I_NCLV /= NCLV ) then
   write(0,'(1x,a,/,6i12)') & 
        & 'I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV=',&
        &  I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV
   write(0,'(1x,a,/,6i12)') & 
        & 'NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV=',&
        &  NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV
   call abor1('Error in CLOUDSC_IN: NCL-variable(s) mismatch')
endif

allocate(YRECLDP)
!read(iu) YRECLDP
!TYPE :: TECLDP
READ(IU) YRECLDP%RAMID
READ(IU) YRECLDP%RCLDIFF
READ(IU) YRECLDP%RCLDIFF_CONVI
READ(IU) YRECLDP%RCLCRIT
READ(IU) YRECLDP%RCLCRIT_SEA
READ(IU) YRECLDP%RCLCRIT_LAND
READ(IU) YRECLDP%RKCONV
READ(IU) YRECLDP%RPRC1
READ(IU) YRECLDP%RPRC2
READ(IU) YRECLDP%RCLDMAX
READ(IU) YRECLDP%RPECONS
READ(IU) YRECLDP%RVRFACTOR
READ(IU) YRECLDP%RPRECRHMAX
READ(IU) YRECLDP%RTAUMEL
READ(IU) YRECLDP%RAMIN
READ(IU) YRECLDP%RLMIN
READ(IU) YRECLDP%RKOOPTAU
READ(IU) YRECLDP%RCLDTOPP
READ(IU) YRECLDP%RLCRITSNOW
READ(IU) YRECLDP%RSNOWLIN1
READ(IU) YRECLDP%RSNOWLIN2
READ(IU) YRECLDP%RICEHI1
READ(IU) YRECLDP%RICEHI2
READ(IU) YRECLDP%RICEINIT
READ(IU) YRECLDP%RVICE
READ(IU) YRECLDP%RVRAIN
READ(IU) YRECLDP%RVSNOW
READ(IU) YRECLDP%RTHOMO
READ(IU) YRECLDP%RCOVPMIN
READ(IU) YRECLDP%RCCN
READ(IU) YRECLDP%RNICE
READ(IU) YRECLDP%RCCNOM
READ(IU) YRECLDP%RCCNSS
READ(IU) YRECLDP%RCCNSU
READ(IU) YRECLDP%RCLDTOPCF
READ(IU) YRECLDP%RDEPLIQREFRATE
READ(IU) YRECLDP%RDEPLIQREFDEPTH
READ(IU) YRECLDP%RCL_KKAac
READ(IU) YRECLDP%RCL_KKBac
READ(IU) YRECLDP%RCL_KKAau
READ(IU) YRECLDP%RCL_KKBauq
READ(IU) YRECLDP%RCL_KKBaun
READ(IU) YRECLDP%RCL_KK_cloud_num_sea
READ(IU) YRECLDP%RCL_KK_cloud_num_land
READ(IU) YRECLDP%RCL_AI
READ(IU) YRECLDP%RCL_BI
READ(IU) YRECLDP%RCL_CI
READ(IU) YRECLDP%RCL_DI
READ(IU) YRECLDP%RCL_X1I
READ(IU) YRECLDP%RCL_X2I
READ(IU) YRECLDP%RCL_X3I
READ(IU) YRECLDP%RCL_X4I
READ(IU) YRECLDP%RCL_CONST1I
READ(IU) YRECLDP%RCL_CONST2I
READ(IU) YRECLDP%RCL_CONST3I
READ(IU) YRECLDP%RCL_CONST4I
READ(IU) YRECLDP%RCL_CONST5I
READ(IU) YRECLDP%RCL_CONST6I
READ(IU) YRECLDP%RCL_APB1
READ(IU) YRECLDP%RCL_APB2
READ(IU) YRECLDP%RCL_APB3
READ(IU) YRECLDP%RCL_AS
READ(IU) YRECLDP%RCL_BS
READ(IU) YRECLDP%RCL_CS
READ(IU) YRECLDP%RCL_DS
READ(IU) YRECLDP%RCL_X1S
READ(IU) YRECLDP%RCL_X2S
READ(IU) YRECLDP%RCL_X3S
READ(IU) YRECLDP%RCL_X4S
READ(IU) YRECLDP%RCL_CONST1S
READ(IU) YRECLDP%RCL_CONST2S
READ(IU) YRECLDP%RCL_CONST3S
READ(IU) YRECLDP%RCL_CONST4S
READ(IU) YRECLDP%RCL_CONST5S
READ(IU) YRECLDP%RCL_CONST6S
READ(IU) YRECLDP%RCL_CONST7S
READ(IU) YRECLDP%RCL_CONST8S
READ(IU) YRECLDP%RDENSWAT
READ(IU) YRECLDP%RDENSREF
READ(IU) YRECLDP%RCL_AR
READ(IU) YRECLDP%RCL_BR
READ(IU) YRECLDP%RCL_CR
READ(IU) YRECLDP%RCL_DR
READ(IU) YRECLDP%RCL_X1R
READ(IU) YRECLDP%RCL_X2R
READ(IU) YRECLDP%RCL_X4R
READ(IU) YRECLDP%RCL_KA273
READ(IU) YRECLDP%RCL_CDENOM1
READ(IU) YRECLDP%RCL_CDENOM2
READ(IU) YRECLDP%RCL_CDENOM3
READ(IU) YRECLDP%RCL_SCHMIDT
READ(IU) YRECLDP%RCL_DYNVISC
READ(IU) YRECLDP%RCL_CONST1R
READ(IU) YRECLDP%RCL_CONST2R
READ(IU) YRECLDP%RCL_CONST3R
READ(IU) YRECLDP%RCL_CONST4R
READ(IU) YRECLDP%RCL_FAC1
READ(IU) YRECLDP%RCL_FAC2
READ(IU) YRECLDP%RCL_CONST5R
READ(IU) YRECLDP%RCL_CONST6R
READ(IU) YRECLDP%RCL_FZRAB
READ(IU) YRECLDP%RCL_FZRBB

READ(IU) II(1), II(2)
YRECLDP%LCLDEXTRA  = (II(1) /= 0)
YRECLDP%LCLDBUDGET = (II(2) /= 0)

READ(IU) YRECLDP%NSSOPT
READ(IU) YRECLDP%NCLDTOP
READ(IU) YRECLDP%NAECLBC, YRECLDP%NAECLDU, YRECLDP%NAECLOM, YRECLDP%NAECLSS, YRECLDP%NAECLSU
READ(IU) YRECLDP%NCLDDIAG
READ(IU) YRECLDP%NAERCLD

READ(IU) II(1)
READ(IU) II(2)
READ(IU) II(3)
READ(IU) II(4)
READ(IU) II(5)
READ(IU) II(6)

YRECLDP%LAERLIQAUTOLSP = (II(1) /= 0)
YRECLDP%LAERLIQAUTOCP = (II(2) /= 0)
YRECLDP%LAERLIQAUTOCPB = (II(3) /= 0)
YRECLDP%LAERLIQCOLL = (II(4) /= 0)
YRECLDP%LAERICESED = (II(5) /= 0)
YRECLDP%LAERICEAUTO = (II(6) /= 0)

READ(IU) YRECLDP%NSHAPEP
READ(IU) YRECLDP%NSHAPEQ
READ(IU) YRECLDP%NBETA
READ(IU) YRECLDP%RBETA(0:100)
READ(IU) YRECLDP%RBETAP1(0:100)
!END TYPE TECLDP

#ifdef DEBUG_OUT
write(0,*) 'CLOUDSC_IN: YRECLDP='
!write(0,*)             YRECLDP ! not used since messy output
COPY_YRECLDP = YRECLDP
write(0,nml=NAM_YRECLDP)
#endif

allocate(YREPHLI)
!read(iu) YREPHLI
! TYPE :: TECLDP
READ(IU) II(1)
READ(IU) II(2)
READ(IU) II(3)
READ(IU) II(4)
READ(IU) II(5)

YREPHLI%LTLEVOL = (II(1) /= 0)
YREPHLI%LPHYLIN = (II(2) /= 0)
YREPHLI%LENOPERT = (II(3) /= 0)
YREPHLI%LEPPCFLS = (II(4) /= 0)
YREPHLI%LRAISANEN = (II(5) /= 0)

READ(IU) YREPHLI%RLPTRC
READ(IU) YREPHLI%RLPAL1
READ(IU) YREPHLI%RLPAL2
READ(IU) YREPHLI%RLPBB
READ(IU) YREPHLI%RLPCC
READ(IU) YREPHLI%RLPDD
READ(IU) YREPHLI%RLPMIXL
READ(IU) YREPHLI%RLPBETA
READ(IU) YREPHLI%RLPDRAG
READ(IU) YREPHLI%RLPEVAP
READ(IU) YREPHLI%RLPP00
!END TYPE TEPHLI

#ifdef DEBUG_OUT
write(0,*) 'CLOUDSC_IN: YREPHLI='
!write(0,*)             YREPHLI ! not used since messy output
COPY_YREPHLI = YREPHLI
write(0,nml=NAM_YREPHLI)
#endif

read(iu) N_VMASS

!USE YOMPHYDER ,ONLY : STATE_TYPE
!type state_type
!  REAL(KIND=JPRB), dimension(:,:), pointer :: u,v,T   ! GMV fields
!  REAL(KIND=JPRB), dimension(:,:), pointer :: o3,q,a  ! GFL fields
!  REAL(KIND=JPRB), dimension(:,:,:), pointer :: cld   ! composed cloud array
!  !REAL(KIND=JPRB), dimension(:,:), pointer :: qsat    ! spec. humidity at saturation
!end type state_type

read(iu) PLCRIT_AER 
read(iu) PICRIT_AER 
read(iu) PRE_ICE 
read(iu) PCCN
read(iu) PNICE
read(iu) PT
read(iu) PQ
read(iu) tendency_cml%u,tendency_cml%v,tendency_cml%T, &
     & tendency_cml%o3,tendency_cml%q,tendency_cml%a, &
     & tendency_cml%cld
read(iu) tendency_tmp%u,tendency_tmp%v,tendency_tmp%T, &
     & tendency_tmp%o3,tendency_tmp%q,tendency_tmp%a, &
     & tendency_tmp%cld
read(iu) PVFA
read(iu) PVFL
read(iu) PVFI
read(iu) PDYNA
read(iu) PDYNL
read(iu) PDYNI
read(iu) PHRSW
read(iu) PHRLW
read(iu) PVERVEL
read(iu) PAP
read(iu) PAPH
read(iu) PLSM
!read(iu) LDCUM
read(iu) I_LDCUM
LDCUM = (I_LDCUM /= 0)
read(iu) KTYPE
read(iu) PLU
read(iu) PLUDE
read(iu) PSNDE
read(iu) PMFU
read(iu) PMFD
read(iu) PA
read(iu) PEXTRA

read(iu) PCLV

read(iu) PSUPSAT

!IF (LHOOK) CALL DR_HOOK('CLOUDSC_IN',1,ZHOOK_HANDLE)

END SUBROUTINE CLOUDSC_IN
