! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

SUBROUTINE CLOUDSC_IN &
 !---input
 & (iu,    KLON,    KLEV,&
 & PTSPHY,&
 & PT, PQ, tendency_cml,tendency_tmp, &
 & PVFA, PVFL, PVFI, PDYNA, PDYNL, PDYNI, &
 & PHRSW,    PHRLW,&
 & PVERVEL,  PAP,      PAPH,&
 & PLSM,     LDCUM,    KTYPE, &
 & PLU,      PLUDE,    PSNDE,    PMFU,     PMFD,&
 & LDSLPHY,  LDMAINCALL, &
 !---prognostic fields
 & PA,&
 & PCLV,  &
 & PSUPSAT, &
!-- arrays for aerosol-cloud interactions
!!! & PQAER,    KAER, &
 & PLCRIT_AER,PICRIT_AER,&
 & PRE_ICE,&
 & PCCN,     PNICE,&
 & PEXTRA,   KFLDX)  

!===============================================================================

USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMPHYDER ,ONLY : STATE_TYPE
!USE YOMHOOK  , ONLY : LHOOK, DR_HOOK
USE YOMMP0   , ONLY : LSCMEC
USE YOMCST   , ONLY : RG, RD, RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV  
USE YOETHF   , ONLY : R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, &
 & R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU, &
 & RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2
USE YOECLDP  , ONLY : YRECLDP, TECLDP, NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV
USE YOMJFH   , ONLY : N_VMASS
USE YOEPHLI  , ONLY : YREPHLI, TEPHLI
USE DIAG_MOD , ONLY : NUMOMP

IMPLICIT NONE

!-------------------------------------------------------------------------------
!                 Declare input/output arguments
!-------------------------------------------------------------------------------

INTEGER(KIND=JPIM), INTENT(in) :: iu
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON             ! Number of grid points
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV             ! Number of levels

REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLCRIT_AER(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PICRIT_AER(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PRE_ICE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PCCN(KLON,KLEV)     ! liquid cloud condensation nuclei
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PNICE(KLON,KLEV)    ! ice number concentration (cf. CCN)

REAL(KIND=JPRB)   ,INTENT(OUT)    :: PTSPHY            ! Physics timestep
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PT(KLON,KLEV)    ! T at start of callpar
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PQ(KLON,KLEV)    ! Q at start of callpar
TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_cml   ! cumulative tendency used for final output
TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_tmp   ! cumulative tendency used as input
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFA(KLON,KLEV)  ! CC from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFL(KLON,KLEV)  ! Liq from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVFI(KLON,KLEV)  ! Ice from VDF scheme
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNA(KLON,KLEV) ! CC from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNL(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PDYNI(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PHRSW(KLON,KLEV) ! Short-wave heating rate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PHRLW(KLON,KLEV) ! Long-wave heating rate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PVERVEL(KLON,KLEV) !Vertical velocity
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PAP(KLON,KLEV)   ! Pressure on full levels
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PAPH(KLON,KLEV+1)! Pressure on half levels
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLSM(KLON)       ! Land fraction (0-1) 
LOGICAL           ,INTENT(OUT)    :: LDCUM(KLON)      ! Convection active
INTEGER(KIND=JPIM),INTENT(OUT)    :: KTYPE(KLON)      ! Convection type 0,1,2
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLU(KLON,KLEV)   ! Conv. condensate
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PLUDE(KLON,KLEV) ! Conv. detrained water 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PSNDE(KLON,KLEV) ! Conv. detrained snow
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PMFU(KLON,KLEV)  ! Conv. mass flux up
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PMFD(KLON,KLEV)  ! Conv. mass flux down
LOGICAL           ,INTENT(OUT)    :: LDSLPHY 
LOGICAL           ,INTENT(OUT)    :: LDMAINCALL       ! T if main call to cloudsc
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PA(KLON,KLEV)    ! Original Cloud fraction (t)

! double precision 

REAL(KIND=JPRD)      :: DP_PLCRIT_AER(KLON,KLEV)
REAL(KIND=JPRD)      :: DP_PICRIT_AER(KLON,KLEV)
REAL(KIND=JPRD)      :: DP_PRE_ICE(KLON,KLEV)
REAL(KIND=JPRD)      :: DP_PCCN(KLON,KLEV)     ! liquid cloud condensation nuclei
REAL(KIND=JPRD)      :: DP_PNICE(KLON,KLEV)    ! ice number concentration (cf. CCN)
REAL(KIND=JPRD)      :: DP_PT(KLON,KLEV)    ! T at start of callpar
REAL(KIND=JPRD)      :: DP_PQ(KLON,KLEV)    ! Q at start of callpar
! TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_cml   ! cumulative tendency used for final output
! TYPE (STATE_TYPE) , INTENT (OUT)  :: tendency_tmp   ! cumulative tendency used as input

! !$loki dimension(klon,klev)
!  REAL(KIND=JPRB), dimension(:,:), pointer :: u,v,T   ! GMV fields
!  !$loki dimension(klon,klev)
!  REAL(KIND=JPRB), dimension(:,:), pointer :: o3,q,a  ! GFL fields
!  !$loki dimension(klon,klev,5)
!  REAL(KIND=JPRB), dimension(:,:,:), pointer :: cld   ! composed cloud array
!  !REAL(KIND=JPRB), dimension(:,:), pointer :: qsat    ! spec. humidity at saturation

REAL(KIND=JPRD)      :: dp_tendency_cml_u(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_v(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_T(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_o3(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_q(KLON,KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_a(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_cml_cld(KLON,KLEV,5)

REAL(KIND=JPRD)      :: dp_tendency_tmp_u(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_v(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_T(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_o3(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_q(KLON,KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_a(KLON, KLEV)
REAL(KIND=JPRD)      :: dp_tendency_tmp_cld(KLON,KLEV,5)

! read(iu) tendency_cml%u,tendency_cml%v,tendency_cml%T, &
!     & tendency_cml%o3,tendency_cml%q,tendency_cml%a, &
!     & tendency_cml%cld

REAL(KIND=JPRD)      :: DP_PVFA(KLON,KLEV)  ! CC from VDF scheme
REAL(KIND=JPRD)      :: DP_PVFL(KLON,KLEV)  ! Liq from VDF scheme
REAL(KIND=JPRD)      :: DP_PVFI(KLON,KLEV)  ! Ice from VDF scheme
REAL(KIND=JPRD)      :: DP_PDYNA(KLON,KLEV) ! CC from Dynamics
REAL(KIND=JPRD)      :: DP_PDYNL(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRD)      :: DP_PDYNI(KLON,KLEV) ! Liq from Dynamics
REAL(KIND=JPRD)      :: DP_PHRSW(KLON,KLEV) ! Short-wave heating rate
REAL(KIND=JPRD)      :: DP_PHRLW(KLON,KLEV) ! Long-wave heating rate
REAL(KIND=JPRD)      :: DP_PVERVEL(KLON,KLEV) !Vertical velocity
REAL(KIND=JPRD)      :: DP_PAP(KLON,KLEV)   ! Pressure on full levels
REAL(KIND=JPRD)      :: DP_PAPH(KLON,KLEV+1)! Pressure on half levels
REAL(KIND=JPRD)      :: DP_PLSM(KLON)       ! Land fraction (0-1) 
REAL(KIND=JPRD)      :: DP_PLU(KLON,KLEV)   ! Conv. condensate
REAL(KIND=JPRD)      :: DP_PLUDE(KLON,KLEV) ! Conv. detrained water 
REAL(KIND=JPRD)      :: DP_PSNDE(KLON,KLEV) ! Conv. detrained snow
REAL(KIND=JPRD)      :: DP_PMFU(KLON,KLEV)  ! Conv. mass flux up
REAL(KIND=JPRD)      :: DP_PMFD(KLON,KLEV)  ! Conv. mass flux down
REAL(KIND=JPRD)      :: DP_PA(KLON,KLEV)    ! Original Cloud fraction (t)
REAL(KIND=JPRD)      :: DP_PEXTRA(KLON,KLEV,KFLDX) ! extra fields
REAL(KIND=JPRD)      :: DP_PCLV(KLON,KLEV,NCLV)
REAL(KIND=JPRD)      :: DP_PSUPSAT(KLON,KLEV)

! end double precision

INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDX 
REAL(KIND=JPRB) ,INTENT(OUT)  :: PEXTRA(KLON,KLEV,KFLDX) ! extra fields

REAL(KIND=JPRB)  ,INTENT(OUT)    :: PCLV(KLON,KLEV,NCLV) 

 ! Supersat clipped at previous time level in SLTEND
REAL(KIND=JPRB)      :: PSUPSAT(KLON,KLEV)

#include "abor1.intfb.h"

REAL(KIND=JPRD) :: TMP, ARRAY_TMP(0:100)
REAL(KIND=JPRB) :: ZDUMMY(1)
REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER(KIND=JPIM)  I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV, II(6)

!-- A trick to get more readable TYPE-struct output: copy type data to namelist !
TYPE(TECLDP) :: COPY_YRECLDP
TYPE(TEPHLI) :: COPY_YREPHLI
namelist/NAM_YRECLDP/ COPY_YRECLDP
namelist/NAM_YREPHLI/ COPY_YREPHLI

!-- We need to read LOGICALs in as 4-byte integers & convert them to LOGICALs based
!   whether they were 0 (= FALSE) or not-0 (= TRUE) 
INTEGER(KIND=JPIM) :: I_LDSLPHY, I_LDMAINCALL, I_LDCUM(KLON)

!IF (LHOOK) CALL DR_HOOK('CLOUDSC_IN',0,ZHOOK_HANDLE)

read(iu) TMP ! PTSPHY
PTSPHY = REAL(TMP, KIND=JPRB)
!read(iu) LDSLPHY
!read(iu) LDMAINCALL
read(iu) I_LDSLPHY
! I_LDSLPHY = REAL(TMP, KIND=JPRB)
LDSLPHY = (I_LDSLPHY /= 0)
read(iu) I_LDMAINCALL
! I_LDMAINCALL = REAL(TMP, KIND=JPRB)
LDMAINCALL = (I_LDMAINCALL /= 0)

1000 format(1x,a,L1)
! # ifdef DEBUG_OUT
write(0,1000) 'CLOUDSC_IN: LDSLPHY=',LDSLPHY
write(0,1000) 'CLOUDSC_IN: LDMAINCALL=',LDMAINCALL
! # endif

print *, "0"

read(iu) LSCMEC
! LSCMEC = REAL(TMP, KIND=JPRB)
read(iu) TMP ! RG, RD, RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV  
RG = REAL(TMP, KIND=JPRB)
read(iu) TMP
RD = REAL(TMP, KIND=JPRB)
read(iu) TMP
RCPD = REAL(TMP, KIND=JPRB)
read(iu) TMP
RETV = REAL(TMP, KIND=JPRB)
read(iu) TMP
RLVTT = REAL(TMP, KIND=JPRB)
read(iu) TMP
RLSTT = REAL(TMP, KIND=JPRB)
read(iu) TMP
RLMLT = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTT = REAL(TMP, KIND=JPRB)
read(iu) TMP
RV = REAL(TMP, KIND=JPRB)
! read(iu)
! = REAL(TMP, KIND=JPRB)

print *, "1"

! read(iu) R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, &
!  & R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU, &
!  & RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2
read(iu) TMP
R2ES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R3LES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R3IES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R4LES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R4IES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R5LES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R5IES = REAL(TMP, KIND=JPRB)
read(iu) TMP
R5ALVCP = REAL(TMP, KIND=JPRB)
read(iu) TMP
R5ALSCP = REAL(TMP, KIND=JPRB)
read(iu) TMP
RALVDCP = REAL(TMP, KIND=JPRB)
read(iu) TMP
RALSDCP = REAL(TMP, KIND=JPRB)
read(iu) TMP
RALFDCP = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTWAT = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTICE = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTICECU = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTWAT_RTICE_R = REAL(TMP, KIND=JPRB)
read(iu) TMP
RTWAT_RTICECU_R = REAL(TMP, KIND=JPRB)
read(iu) TMP
RKOOP1 = REAL(TMP, KIND=JPRB)
read(iu) TMP
RKOOP2 = REAL(TMP, KIND=JPRB)
! read(iu) TMP
!  = REAL(TMP, KIND=JPRB)

print *, "2"

read(iu) I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV

if ( I_NCLDQV /= NCLDQV .or. &
   & I_NCLDQL /= NCLDQL .or. &
   & I_NCLDQR /= NCLDQR .or. &
   & I_NCLDQI /= NCLDQI .or. &
   & I_NCLV /= NCLV ) then
   write(0,'(1x,a,/,6i12)') & 
        & 'I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV=',&
        &  I_NCLDQV, I_NCLDQL, I_NCLDQR, I_NCLDQI, I_NCLDQS, I_NCLV
   write(0,'(1x,a,/,6i12)') & 
        & 'NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV=',&
        &  NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV
   call abor1('Error in CLOUDSC_IN: NCL-variable(s) mismatch')
endif

allocate(YRECLDP)
!read(iu) YRECLDP
!TYPE :: TECLDP

READ(IU) TMP ! YRECLDP%RAMID
YRECLDP%RAMID = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLDIFF
YRECLDP%RCLDIFF = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLDIFF_CONVI
YRECLDP%RCLDIFF_CONVI = REAL(TMP, KIND=JPRB)

print *, "YRECLDP%RCLDIFF_CONVI: ", YRECLDP%RCLDIFF_CONVI

READ(IU) TMP ! YRECLDP%RCLCRIT
YRECLDP%RCLCRIT = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLCRIT_SEA
YRECLDP%RCLCRIT_SEA = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLCRIT_LAND
YRECLDP%RCLCRIT_LAND = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RKCONV
YRECLDP%RKCONV = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RPRC1
YRECLDP%RPRC1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RPRC2
YRECLDP%RPRC2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLDMAX
YRECLDP%RCLDMAX = REAL(TMP, KIND=JPRB)

print *, "YRECLDP%RCLDMAX: ", YRECLDP%RCLDMAX

READ(IU) TMP ! YRECLDP%RPECONS
YRECLDP%RPECONS = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RVRFACTOR
YRECLDP%RVRFACTOR = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RPRECRHMAX
YRECLDP%RPRECRHMAX = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RTAUMEL
YRECLDP%RTAUMEL = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RAMIN
YRECLDP%RAMIN = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RLMIN
YRECLDP%RLMIN = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RKOOPTAU
YRECLDP%RKOOPTAU = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLDTOPP
YRECLDP%RCLDTOPP = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RLCRITSNOW
YRECLDP%RLCRITSNOW = REAL(TMP, KIND=JPRB)

print *, "YRECLDP%RLCRITSNOW: ", YRECLDP%RLCRITSNOW

READ(IU) TMP ! YRECLDP%RSNOWLIN1
YRECLDP%RSNOWLIN1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RSNOWLIN2
YRECLDP%RSNOWLIN2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RICEHI1
YRECLDP%RICEHI1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RICEHI2
YRECLDP%RICEHI2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RICEINIT
YRECLDP%RICEINIT = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RVICE
YRECLDP%RVICE = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RVRAIN
YRECLDP%RVRAIN = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RVSNOW
YRECLDP%RVSNOW = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RTHOMO
YRECLDP%RTHOMO = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCOVPMIN
YRECLDP%RCOVPMIN = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCCN
YRECLDP%RCCN = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RNICE
YRECLDP%RNICE = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCCNOM
YRECLDP%RCCNOM = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCCNSS
YRECLDP%RCCNSS = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCCNSU
YRECLDP%RCCNSU = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCLDTOPCF
YRECLDP%RCLDTOPCF = REAL(TMP, KIND=JPRB)

print *, "YRECLDP%RCLDTOPCF: ", YRECLDP%RCLDTOPCF

READ(IU) TMP ! YRECLDP%RDEPLIQREFRATE
YRECLDP%RDEPLIQREFRATE = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RDEPLIQREFDEPTH
YRECLDP%RDEPLIQREFDEPTH = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KKAac
YRECLDP%RCL_KKAac = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KKBac
YRECLDP%RCL_KKBac = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KKAau
YRECLDP%RCL_KKAau = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KKBauq
YRECLDP%RCL_KKBauq = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KKBaun
YRECLDP%RCL_KKBaun = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KK_cloud_num_sea
YRECLDP%RCL_KK_cloud_num_sea = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KK_cloud_num_land
YRECLDP%RCL_KK_cloud_num_land = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_AI
YRECLDP%RCL_AI = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_BI
YRECLDP%RCL_BI = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CI
YRECLDP%RCL_CI = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_DI
YRECLDP%RCL_DI = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X1I
YRECLDP%RCL_X1I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X2I
YRECLDP%RCL_X2I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X3I
YRECLDP%RCL_X3I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X4I
YRECLDP%RCL_X4I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST1I
YRECLDP%RCL_CONST1I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST2I
YRECLDP%RCL_CONST2I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST3I
YRECLDP%RCL_CONST3I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST4I
YRECLDP%RCL_CONST4I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST5I
YRECLDP%RCL_CONST5I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST6I
YRECLDP%RCL_CONST6I = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_APB1
YRECLDP%RCL_APB1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_APB2
YRECLDP%RCL_APB2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_APB3
YRECLDP%RCL_APB3 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_AS
YRECLDP%RCL_AS = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_BS
YRECLDP%RCL_BS = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CS
YRECLDP%RCL_CS = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_DS
YRECLDP%RCL_DS = REAL(TMP, KIND=JPRB)

print *, "YRECLDP%RCL_DS: ", YRECLDP%RCL_DS

READ(IU) TMP ! YRECLDP%RCL_X1S
YRECLDP%RCL_X1S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X2S
YRECLDP%RCL_X2S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X3S
YRECLDP%RCL_X3S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X4S
YRECLDP%RCL_X4S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST1S
YRECLDP%RCL_CONST1S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST2S
YRECLDP%RCL_CONST2S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST3S
YRECLDP%RCL_CONST3S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST4S
YRECLDP%RCL_CONST4S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST5S
YRECLDP%RCL_CONST5S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST6S
YRECLDP%RCL_CONST6S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST7S
YRECLDP%RCL_CONST7S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST8S
YRECLDP%RCL_CONST8S = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RDENSWAT
YRECLDP%RDENSWAT = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RDENSREF
YRECLDP%RDENSREF = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_AR
YRECLDP%RCL_AR = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_BR
YRECLDP%RCL_BR = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CR
YRECLDP%RCL_CR = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_DR
YRECLDP%RCL_DR = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X1R
YRECLDP%RCL_X1R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X2R
YRECLDP%RCL_X2R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_X4R
YRECLDP%RCL_X4R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_KA273
YRECLDP%RCL_KA273 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CDENOM1
YRECLDP%RCL_CDENOM1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CDENOM2
YRECLDP%RCL_CDENOM2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CDENOM3
YRECLDP%RCL_CDENOM3 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_SCHMIDT
YRECLDP%RCL_SCHMIDT = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_DYNVISC
YRECLDP%RCL_DYNVISC = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST1R
YRECLDP%RCL_CONST1R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST2R
YRECLDP%RCL_CONST2R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST3R
YRECLDP%RCL_CONST3R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST4R
YRECLDP%RCL_CONST4R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_FAC1
YRECLDP%RCL_FAC1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_FAC2
YRECLDP%RCL_FAC2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST5R
YRECLDP%RCL_CONST5R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_CONST6R
YRECLDP%RCL_CONST6R = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_FZRAB
YRECLDP%RCL_FZRAB = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%RCL_FZRBB
YRECLDP%RCL_FZRBB = REAL(TMP, KIND=JPRB)

READ(IU) II(1), II(2)
YRECLDP%LCLDEXTRA  = (II(1) /= 0)
YRECLDP%LCLDBUDGET = (II(2) /= 0)

! INTEGER
READ(IU) YRECLDP%NSSOPT 
READ(IU) YRECLDP%NCLDTOP
READ(IU) YRECLDP%NAECLBC, YRECLDP%NAECLDU, YRECLDP%NAECLOM, YRECLDP%NAECLSS, YRECLDP%NAECLSU
READ(IU) YRECLDP%NCLDDIAG
READ(IU) YRECLDP%NAERCLD

print *, "YRECLDP%NSSOPT: ", YRECLDP%NSSOPT
print *, "YRECLDP%NCLDTOP: ", YRECLDP%NCLDTOP
print *, "YRECLDP%NAECLBC: ", YRECLDP%NAECLBC
print *, "YRECLDP%NAECLDU: ", YRECLDP%NAECLDU
print *, "YRECLDP%NAECLOM: ", YRECLDP%NAECLOM

READ(IU) II(1)
READ(IU) II(2)
READ(IU) II(3)
READ(IU) II(4)
READ(IU) II(5)
READ(IU) II(6)

YRECLDP%LAERLIQAUTOLSP = (II(1) /= 0)
YRECLDP%LAERLIQAUTOCP = (II(2) /= 0)
YRECLDP%LAERLIQAUTOCPB = (II(3) /= 0)
YRECLDP%LAERLIQCOLL = (II(4) /= 0)
YRECLDP%LAERICESED = (II(5) /= 0)
YRECLDP%LAERICEAUTO = (II(6) /= 0)

READ(IU) TMP ! YRECLDP%NSHAPEP
YRECLDP%NSHAPEP = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YRECLDP%NSHAPEQ
YRECLDP%NSHAPEQ = REAL(TMP, KIND=JPRB)
READ(IU) YRECLDP%NBETA ! INTEGER
READ(IU) ARRAY_TMP(0:100) ! YRECLDP%RBETA(0:100)
YRECLDP%RBETA(0:100) = REAL(ARRAY_TMP(0:100), KIND=JPRB)
READ(IU) ARRAY_TMP(0:100) ! YRECLDP%RBETAP1(0:100)
YRECLDP%RBETAP1(0:100) = REAL(ARRAY_TMP(0:100), KIND=JPRB)
!END TYPE TECLDP

print *, "YRECLDP%NBETA: ", YRECLDP%NBETA
#ifdef DEBUG_OUT
write(0,*) 'CLOUDSC_IN: YRECLDP='
!write(0,*)             YRECLDP ! not used since messy output
COPY_YRECLDP = YRECLDP
write(0,nml=NAM_YRECLDP)
#endif

allocate(YREPHLI)
!read(iu) YREPHLI
! TYPE :: TECLDP
READ(IU) II(1)
READ(IU) II(2)
READ(IU) II(3)
READ(IU) II(4)
READ(IU) II(5)

YREPHLI%LTLEVOL = (II(1) /= 0)
YREPHLI%LPHYLIN = (II(2) /= 0)
YREPHLI%LENOPERT = (II(3) /= 0)
YREPHLI%LEPPCFLS = (II(4) /= 0)
YREPHLI%LRAISANEN = (II(5) /= 0)

READ(IU) TMP ! YREPHLI%RLPTRC
YREPHLI%RLPTRC = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPAL1
YREPHLI%RLPAL1 = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPAL2
YREPHLI%RLPAL2 = REAL(TMP, KIND=JPRB)
READ(IU) TMP !YREPHLI%RLPBB
YREPHLI%RLPBB = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPCC
YREPHLI%RLPCC = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPDD
YREPHLI%RLPDD = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPMIXL
YREPHLI%RLPMIXL = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPBETA
YREPHLI%RLPBETA = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPDRAG
YREPHLI%RLPDRAG = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPEVAP
YREPHLI%RLPEVAP = REAL(TMP, KIND=JPRB)
READ(IU) TMP ! YREPHLI%RLPP00
YREPHLI%RLPP00 = REAL(TMP, KIND=JPRB)
!END TYPE TEPHLI

print *, "YREPHLI%RLPP00: ", YREPHLI%RLPP00

#ifdef DEBUG_OUT
write(0,*) 'CLOUDSC_IN: YREPHLI='
!write(0,*)             YREPHLI ! not used since messy output
COPY_YREPHLI = YREPHLI
write(0,nml=NAM_YREPHLI)
#endif

read(iu) N_VMASS

!USE YOMPHYDER ,ONLY : STATE_TYPE
!type state_type
!  REAL(KIND=JPRB), dimension(:,:), pointer :: u,v,T   ! GMV fields
!  REAL(KIND=JPRB), dimension(:,:), pointer :: o3,q,a  ! GFL fields
!  REAL(KIND=JPRB), dimension(:,:,:), pointer :: cld   ! composed cloud array
!  !REAL(KIND=JPRB), dimension(:,:), pointer :: qsat    ! spec. humidity at saturation
!end type state_type

read(iu) DP_PLCRIT_AER ! PLCRIT_AER 
PLCRIT_AER = REAL(DP_PLCRIT_AER, KIND=JPRB)
read(iu) DP_PICRIT_AER ! PICRIT_AER 
PICRIT_AER = REAL(DP_PICRIT_AER, KIND=JPRB) 
read(iu) DP_PRE_ICE ! PRE_ICE 
PRE_ICE = REAL(DP_PRE_ICE, KIND=JPRB) 
read(iu) DP_PCCN ! PCCN
PCCN = REAL(DP_PCCN, KIND=JPRB)
read(iu) DP_PNICE ! PNICE
PNICE = REAL(DP_PNICE, KIND=JPRB)
read(iu) DP_PT ! PT
PT = REAL(DP_PT, KIND=JPRB)
read(iu) DP_PQ! PQ
PQ = REAL(DP_PQ, KIND=JPRB)
!read(iu) tendency_cml%u,tendency_cml%v,tendency_cml%T, &
!     & tendency_cml%o3,tendency_cml%q,tendency_cml%a, &
!     & tendency_cml%cld
read(iu) dp_tendency_cml_u
tendency_cml%u = REAL(dp_tendency_cml_u, KIND=JPRB) 
read(iu) dp_tendency_cml_v
tendency_cml%v = REAL(dp_tendency_cml_v, KIND=JPRB)
read(iu) dp_tendency_cml_T
tendency_cml%T = REAL(dp_tendency_cml_T, KIND=JPRB)
read(iu) dp_tendency_cml_o3
tendency_cml%o3 = REAL(dp_tendency_cml_o3, KIND=JPRB)
read(iu) dp_tendency_cml_q
tendency_cml%q = REAL(dp_tendency_cml_q, KIND=JPRB)
read(iu) dp_tendency_cml_a
tendency_cml%a = REAL(dp_tendency_cml_a, KIND=JPRB)
read(iu) dp_tendency_cml_cld
tendency_cml%cld = REAL(dp_tendency_cml_cld, KIND=JPRB)
!read(iu) tendency_tmp%u,tendency_tmp%v,tendency_tmp%T, &
!     & tendency_tmp%o3,tendency_tmp%q,tendency_tmp%a, &
!     & tendency_tmp%cld
read(iu) dp_tendency_tmp_u
tendency_tmp%u = REAL(dp_tendency_tmp_u, KIND=JPRB)
read(iu) dp_tendency_tmp_v
tendency_tmp%v = REAL(dp_tendency_tmp_v, KIND=JPRB)
read(iu) dp_tendency_tmp_T
tendency_tmp%T = REAL(dp_tendency_tmp_T, KIND=JPRB)
read(iu) dp_tendency_tmp_o3
tendency_tmp%o3 = REAL(dp_tendency_tmp_o3, KIND=JPRB)
read(iu) dp_tendency_tmp_q
tendency_tmp%q = REAL(dp_tendency_tmp_q, KIND=JPRB)
read(iu) dp_tendency_tmp_a
tendency_tmp%a = REAL(dp_tendency_tmp_a, KIND=JPRB)
read(iu) dp_tendency_tmp_cld
tendency_tmp%cld = REAL(dp_tendency_tmp_cld, KIND=JPRB)

read(iu) DP_PVFA ! PVFA
PVFA = REAL(DP_PVFA, KIND=JPRB)
read(iu) DP_PVFL ! PVFL
PVFL = REAL(DP_PVFL, KIND=JPRB)
read(iu) DP_PVFI ! PVFI
PVFI = REAL(DP_PVFI, KIND=JPRB)
read(iu) DP_PDYNA ! PDYNA
PDYNA = REAL(DP_PDYNA, KIND=JPRB)
read(iu) DP_PDYNL ! PDYNL
PDYNL = REAL(DP_PDYNL, KIND=JPRB)
read(iu) DP_PDYNI ! PDYNI
PDYNI = REAL(DP_PDYNI, KIND=JPRB)
read(iu) DP_PHRSW ! PHRSW
PHRSW = REAL(DP_PHRSW, KIND=JPRB)
read(iu) DP_PHRLW ! PHRLW
PHRLW = REAL(DP_PHRLW, KIND=JPRB)
read(iu) DP_PVERVEL ! PVERVEL
PVERVEL = REAL(DP_PVERVEL, KIND=JPRB)
read(iu) DP_PAP ! PAP
PAP = REAL(DP_PAP, KIND=JPRB)
read(iu) DP_PAPH ! PAPH
PAPH = REAL(DP_PAPH, KIND=JPRB)
read(iu) DP_PLSM ! PLSM
PLSM = REAL(DP_PLSM, KIND=JPRB)
!read(iu) LDCUM
read(iu) I_LDCUM
LDCUM = (I_LDCUM /= 0)
read(iu) KTYPE
read(iu) DP_PLU ! PLU
PLU = REAL(DP_PLU, KIND=JPRB)
read(iu) DP_PLUDE ! PLUDE
PLUDE = REAL(DP_PLUDE, KIND=JPRB)
read(iu) DP_PSNDE ! PSNDE
PSNDE = REAL(DP_PSNDE, KIND=JPRB)
read(iu) DP_PMFU ! PMFU
PMFU = REAL(DP_PMFU, KIND=JPRB)
read(iu) DP_PMFD ! PMFD
PMFD = REAL(DP_PMFD, KIND=JPRB)
read(iu) DP_PA ! PA
PA = REAL(DP_PA, KIND=JPRB)
read(iu) DP_PEXTRA ! PEXTRA
PEXTRA = REAL(DP_PEXTRA, KIND=JPRB)

read(iu) DP_PCLV ! PCLV
PCLV = REAL(DP_PCLV, KIND=JPRB)

read(iu) DP_PSUPSAT ! PSUPSAT
PSUPSAT = REAL(DP_PSUPSAT, KIND=JPRB)

!IF (LHOOK) CALL DR_HOOK('CLOUDSC_IN',1,ZHOOK_HANDLE)

END SUBROUTINE CLOUDSC_IN
