! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM DWARF_CLOUDSC

USE PARKIND1, ONLY: JPIM, JPIB
USE CLOUDSC_MPI_MOD, ONLY: CLOUDSC_MPI_INIT, CLOUDSC_MPI_END, NUMPROC, IRANK
USE CLOUDSC_GLOBAL_ATLAS_STATE_MOD, ONLY: CLOUDSC_GLOBAL_ATLAS_STATE
USE CLOUDSC_DRIVER_MOD, ONLY: CLOUDSC_DRIVER
USE EC_PMON_MOD, ONLY: EC_PMON

USE ATLAS_MODULE
USE, INTRINSIC :: ISO_C_BINDING

IMPLICIT NONE

CHARACTER(LEN=20) :: CLARG
INTEGER(KIND=JPIM) :: IARGS, LENARG, JARG, I

INTEGER(KIND=JPIM) :: NUMOMP   = 1     ! Number of OpenMP threads for this run
INTEGER(KIND=JPIM) :: NGPTOTG  = 16384 ! Number of grid points (as read from command line)
INTEGER(KIND=JPIM) :: NPROMA   = 32    ! NPROMA blocking factor (currently active)
INTEGER(KIND=JPIM) :: NGPTOT           ! Local number of grid points

TYPE(CLOUDSC_GLOBAL_ATLAS_STATE) :: GLOBAL_ATLAS_STATE

INTEGER(KIND=JPIB) :: ENERGY, POWER
CHARACTER(LEN=1)   :: CLEC_PMON

CALL GET_ENVIRONMENT_VARIABLE('EC_PMON', CLEC_PMON)
IF (CLEC_PMON == '1') THEN
  CALL EC_PMON(ENERGY, POWER)
  print *, "EC_PMON:: Initial (idle) power: ", POWER
END IF

IARGS = COMMAND_ARGUMENT_COUNT()

! Get the number of OpenMP threads to use for the benchmark
if (IARGS >= 1) then
   CALL GET_COMMAND_ARGUMENT(1, CLARG, LENARG)
   READ(CLARG(1:LENARG),*) NUMOMP
end if

! Initialize MPI environment
CALL ATLAS_LIBRARY%INITIALISE()
CALL CLOUDSC_MPI_INIT(NUMOMP)

! Get total number of grid points (NGPTOT) with which to run the benchmark
IF (IARGS >= 2) THEN
  CALL GET_COMMAND_ARGUMENT(2, CLARG, LENARG)
  READ(CLARG(1:LENARG),*) NGPTOTG
END IF

! Determine local number of grid points
NGPTOT = (NGPTOTG - 1) / NUMPROC + 1
if (IRANK == NUMPROC - 1) then
  NGPTOT = NGPTOTG - (NUMPROC - 1) * NGPTOT
end if

! Get the block size (NPROMA) for which to run the benchmark  
IF (IARGS >= 3) THEN
  CALL GET_COMMAND_ARGUMENT(3, CLARG, LENARG)
  READ(CLARG(1:LENARG),*) NPROMA
ENDIF

! TODO: Create a global global memory state from serialized input data
CALL GLOBAL_ATLAS_STATE%LOAD(NPROMA, NGPTOT, NGPTOTG)

! Call the driver to perform the parallel loop over our kernel
CALL CLOUDSC_DRIVER(NUMOMP, NPROMA, GLOBAL_ATLAS_STATE%KLEV, NGPTOT, NGPTOTG, &
     & GLOBAL_ATLAS_STATE%KFLDX, GLOBAL_ATLAS_STATE%PTSPHY, &
     & GLOBAL_ATLAS_STATE%PT, GLOBAL_ATLAS_STATE%PQ, &
     & GLOBAL_ATLAS_STATE%TENDENCY_CML, GLOBAL_ATLAS_STATE%TENDENCY_TMP, GLOBAL_ATLAS_STATE%TENDENCY_LOC, &
     & GLOBAL_ATLAS_STATE%PVFA,    GLOBAL_ATLAS_STATE%PVFL,  GLOBAL_ATLAS_STATE%PVFI, &
     & GLOBAL_ATLAS_STATE%PDYNA,   GLOBAL_ATLAS_STATE%PDYNL, GLOBAL_ATLAS_STATE%PDYNI, &
     & GLOBAL_ATLAS_STATE%PHRSW,   GLOBAL_ATLAS_STATE%PHRLW, &
     & GLOBAL_ATLAS_STATE%PVERVEL, GLOBAL_ATLAS_STATE%PAP,   GLOBAL_ATLAS_STATE%PAPH, &
     & GLOBAL_ATLAS_STATE%PLSM,    GLOBAL_ATLAS_STATE%LDCUM, GLOBAL_ATLAS_STATE%KTYPE, &
     & GLOBAL_ATLAS_STATE%PLU,     GLOBAL_ATLAS_STATE%PLUDE, GLOBAL_ATLAS_STATE%PSNDE, &
     & GLOBAL_ATLAS_STATE%PMFU,    GLOBAL_ATLAS_STATE%PMFD, &
     & GLOBAL_ATLAS_STATE%PA,      GLOBAL_ATLAS_STATE%PCLV,  GLOBAL_ATLAS_STATE%PSUPSAT,&
     & GLOBAL_ATLAS_STATE%PLCRIT_AER, GLOBAL_ATLAS_STATE%PICRIT_AER, GLOBAL_ATLAS_STATE%PRE_ICE, &
     & GLOBAL_ATLAS_STATE%PCCN,     GLOBAL_ATLAS_STATE%PNICE,&
     & GLOBAL_ATLAS_STATE%PCOVPTOT, GLOBAL_ATLAS_STATE%PRAINFRAC_TOPRFZ, &
     & GLOBAL_ATLAS_STATE%PFSQLF,   GLOBAL_ATLAS_STATE%PFSQIF ,  GLOBAL_ATLAS_STATE%PFCQNNG,  GLOBAL_ATLAS_STATE%PFCQLNG, &
     & GLOBAL_ATLAS_STATE%PFSQRF,   GLOBAL_ATLAS_STATE%PFSQSF ,  GLOBAL_ATLAS_STATE%PFCQRNG,  GLOBAL_ATLAS_STATE%PFCQSNG, &
     & GLOBAL_ATLAS_STATE%PFSQLTUR, GLOBAL_ATLAS_STATE%PFSQITUR, &
     & GLOBAL_ATLAS_STATE%PFPLSL,   GLOBAL_ATLAS_STATE%PFPLSN,   GLOBAL_ATLAS_STATE%PFHPSL,   GLOBAL_ATLAS_STATE%PFHPSN &
     & )

! Validate the output against serialized reference data
!CALL GLOBAL_ATLAS_STATE%VALIDATE(NGPTOT, NGPTOTG)

CALL ATLAS_LIBRARY%FINALISE()

! Tear down MPI environment
CALL CLOUDSC_MPI_END()

END PROGRAM DWARF_CLOUDSC
