! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE CLOUDSC_AUX_TYPE_MOD
  USE PARKIND1,  ONLY : JPIM, JPRB
  USE YOECLDP,   ONLY : NCLV

  USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2IM, FIELD_2LM, FIELD_3RB_PTR
  USE FIELD_FACTORY_MODULE, ONLY: FIELD_NEW, FIELD_DELETE

  IMPLICIT NONE

  TYPE CLOUDSC_AUX_TYPE
  
    INTEGER(KIND=JPIM) :: NLEV
    LOGICAL :: PACKED
    ! 2D Fields
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLSM(:)       ! Land fraction (0-1)
    LOGICAL,         POINTER, CONTIGUOUS :: LDCUM(:)      ! Convection active
    INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: KTYPE(:)   ! Convection type 0,1,2
    ! 3D Fields   
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLCRIT_AER(:,:)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PICRIT_AER(:,:)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PRE_ICE(:,:)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCCN(:,:)     ! liquid cloud condensation nuclei
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PNICE(:,:)    ! ice number concentration (cf. CCN)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PT(:,:)       ! T at start of callpar
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PQ(:,:)       ! Q at start of callpar
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFA(:,:)     ! CC from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFL(:,:)     ! Liq from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFI(:,:)     ! Ice from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNA(:,:)    ! CC from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNL(:,:)    ! Liq from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNI(:,:)    ! Liq from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHRSW(:,:)    ! Short-wave heating rate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHRLW(:,:)    ! Long-wave heating rate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVERVEL(:,:)  ! Vertical velocity
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAP(:,:)      ! Pressure on full levels
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAPH(:,:)     ! Pressure on half levels
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLU(:,:)      ! Conv. condensate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLUDE(:,:)    ! Conv. detrained water
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSNDE(:,:)    ! Conv. detrained snow
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PMFU(:,:)     ! Conv. mass flux up
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PMFD(:,:)     ! Conv. mass flux down
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PA(:,:)       ! Original Cloud fraction (t)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PEXTRA(:,:,:) ! extra fields
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLV(:,:,:)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSUPSAT(:,:)
    ! Output fields used for validation
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCOVPTOT(:,:) ! Precip fraction
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PRAINFRAC_TOPRFZ(:)
    
    ! field gang for 3D fields
    CLASS(FIELD_4RB), POINTER :: DATA_RDONLY
    ! Acces pointers for 3D fields in gang
    TYPE(FIELD_3RB_PTR), PRIVATE, ALLOCATABLE :: FIELDS_RDONLY(:)
  
    CLASS(FIELD_2IM), POINTER :: F_KTYPE
    CLASS(FIELD_2LM), POINTER :: F_LDCUM
    CLASS(FIELD_2RB), POINTER :: F_PLSM, F_PRAINFRAC_TOPRFZ
    CLASS(FIELD_3RB), POINTER :: F_PLCRIT_AER, F_PICRIT_AER, F_PRE_ICE, F_PCCN, &
        F_PNICE, F_PT, F_PQ, F_PVFA, F_PVFL, F_PVFI, F_PDYNA, F_PDYNL, F_PDYNI, &
        F_PHRSW, F_PHRLW, F_PVERVEL, F_PAP, F_PAPH, F_PLU, F_PLUDE, F_PSNDE,    &
        F_PMFU, F_PMFD, F_PA, F_PSUPSAT, F_PCOVPTOT
    CLASS(FIELD_4RB), POINTER :: F_PEXTRA, F_PCLV
  
  CONTAINS
    PROCEDURE :: INIT => AUX_TYPE_INIT
    PROCEDURE :: UPDATE_VIEW => AUX_TYPE_UPDATE_VIEW
    PROCEDURE :: SYNC_HOST => AUX_TYPE_SYNC_HOST
    PROCEDURE :: FINAL => AUX_TYPE_FINAL
  
  END TYPE CLOUDSC_AUX_TYPE
  
CONTAINS

  SUBROUTINE AUX_TYPE_INIT(SELF,NPROMA, NGPTOT, KLON, KLEV, KFLDX, NBLOCKS, NGPTOTG, USE_PACKED)
    CLASS(CLOUDSC_AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPTOT, KLON, KLEV, KFLDX, NBLOCKS 
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: NGPTOTG
    LOGICAL, INTENT(IN), OPTIONAL :: USE_PACKED
    
    INTEGER(KIND=JPIM), PARAMETER :: NFIELDS = 23

    SELF%PACKED = .FALSE.
    IF (PRESENT(USE_PACKED)) SELF%PACKED = USE_PACKED

    ! 2D Fields  
    CALL FIELD_NEW(SELF%F_PLSM, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_LDCUM, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_KTYPE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    ! 3D special fields
    CALL FIELD_NEW(SELF%F_PLUDE, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.) ! RDWR field
    CALL FIELD_NEW(SELF%F_PAPH, UBOUNDS=[NPROMA, KLEV+1, NBLOCKS], PERSISTENT=.TRUE.)
    ! 4D Fields 
    CALL FIELD_NEW(SELF%F_PEXTRA, UBOUNDS=[NPROMA,KLEV,NCLV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PCLV, UBOUNDS=[NPROMA,KLEV,NCLV,NBLOCKS], PERSISTENT=.TRUE.)
    ! Validation Fields 
    CALL FIELD_NEW(SELF%F_PCOVPTOT, UBOUNDS=[NPROMA,KLEV,NBLOCKS], PERSISTENT=.TRUE., INIT_VALUE=0._JPRB)
    CALL FIELD_NEW(SELF%F_PRAINFRAC_TOPRFZ, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE., INIT_VALUE=0._JPRB)
    
    ! 3D rdonly fields
    IF (SELF%PACKED) THEN
      CALL FIELD_NEW(SELF%DATA_RDONLY, SELF%FIELDS_RDONLY, UBOUNDS=[NPROMA, KLEV, NFIELDS, NBLOCKS], &
      &                          PERSISTENT=.TRUE.)
      SELF%F_PLCRIT_AER   =>  SELF%FIELDS_RDONLY(1)%PTR
      SELF%F_PICRIT_AER   =>  SELF%FIELDS_RDONLY(2)%PTR
      SELF%F_PRE_ICE      =>  SELF%FIELDS_RDONLY(3)%PTR
      SELF%F_PCCN         =>  SELF%FIELDS_RDONLY(4)%PTR
      SELF%F_PNICE        =>  SELF%FIELDS_RDONLY(5)%PTR
      SELF%F_PT           =>  SELF%FIELDS_RDONLY(6)%PTR
      SELF%F_PQ           =>  SELF%FIELDS_RDONLY(7)%PTR
      SELF%F_PVFA         =>  SELF%FIELDS_RDONLY(8)%PTR
      SELF%F_PVFL         =>  SELF%FIELDS_RDONLY(9)%PTR
      SELF%F_PVFI         =>  SELF%FIELDS_RDONLY(10)%PTR
      SELF%F_PDYNA        =>  SELF%FIELDS_RDONLY(11)%PTR
      SELF%F_PDYNL        =>  SELF%FIELDS_RDONLY(12)%PTR
      SELF%F_PDYNI        =>  SELF%FIELDS_RDONLY(13)%PTR
      SELF%F_PHRSW        =>  SELF%FIELDS_RDONLY(14)%PTR
      SELF%F_PHRLW        =>  SELF%FIELDS_RDONLY(15)%PTR
      SELF%F_PVERVEL      =>  SELF%FIELDS_RDONLY(16)%PTR
      SELF%F_PAP          =>  SELF%FIELDS_RDONLY(17)%PTR
      SELF%F_PLU          =>  SELF%FIELDS_RDONLY(18)%PTR
      SELF%F_PSNDE        =>  SELF%FIELDS_RDONLY(19)%PTR
      SELF%F_PMFU         =>  SELF%FIELDS_RDONLY(20)%PTR
      SELF%F_PMFD         =>  SELF%FIELDS_RDONLY(21)%PTR
      SELF%F_PA           =>  SELF%FIELDS_RDONLY(22)%PTR
      SELF%F_PSUPSAT      =>  SELF%FIELDS_RDONLY(23)%PTR
    ELSE
      CALL FIELD_NEW(SELF%F_PLCRIT_AER, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PICRIT_AER, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PRE_ICE, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PCCN, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PNICE, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PT, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PQ, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PVFA, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PVFL, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PVFI, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PDYNA, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PDYNL, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PDYNI, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PHRSW, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PHRLW, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PVERVEL, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PAP, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PLU, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PSNDE, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PMFU, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PMFD, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PA, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
      CALL FIELD_NEW(SELF%F_PSUPSAT, UBOUNDS=[NPROMA, KLEV, NBLOCKS], PERSISTENT=.TRUE.)
    END IF
  END SUBROUTINE AUX_TYPE_INIT

  SUBROUTINE AUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(CLOUDSC_AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    
    ! 2D fields
    IF(ASSOCIATED(SELF%F_PLSM)) SELF%PLSM => SELF%F_PLSM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LDCUM)) SELF%LDCUM => SELF%F_LDCUM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_KTYPE)) SELF%KTYPE => SELF%F_KTYPE%GET_VIEW(BLOCK_INDEX)
    ! 3D Fields
    IF(ASSOCIATED(SELF%F_PLCRIT_AER)) SELF%PLCRIT_AER => SELF%F_PLCRIT_AER%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PICRIT_AER)) SELF%PICRIT_AER => SELF%F_PICRIT_AER%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRE_ICE)) SELF%PRE_ICE => SELF%F_PRE_ICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCCN)) SELF%PCCN => SELF%F_PCCN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PNICE)) SELF%PNICE => SELF%F_PNICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PT)) SELF%PT => SELF%F_PT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PQ)) SELF%PQ => SELF%F_PQ%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVFA)) SELF%PVFA => SELF%F_PVFA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVFL)) SELF%PVFL => SELF%F_PVFL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVFI)) SELF%PVFI => SELF%F_PVFI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDYNA)) SELF%PDYNA => SELF%F_PDYNA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDYNL)) SELF%PDYNL => SELF%F_PDYNL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDYNI)) SELF%PDYNI => SELF%F_PDYNI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHRSW)) SELF%PHRSW => SELF%F_PHRSW%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHRLW)) SELF%PHRLW => SELF%F_PHRLW%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVERVEL)) SELF%PVERVEL => SELF%F_PVERVEL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAP)) SELF%PAP => SELF%F_PAP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAPH)) SELF%PAPH => SELF%F_PAPH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLU)) SELF%PLU => SELF%F_PLU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLUDE)) SELF%PLUDE => SELF%F_PLUDE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSNDE)) SELF%PSNDE => SELF%F_PSNDE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PMFU)) SELF%PMFU => SELF%F_PMFU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PMFD)) SELF%PMFD => SELF%F_PMFD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PA)) SELF%PA => SELF%F_PA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSUPSAT)) SELF%PSUPSAT => SELF%F_PSUPSAT%GET_VIEW(BLOCK_INDEX)
    ! 4D fields 
    IF(ASSOCIATED(SELF%F_PEXTRA)) SELF%PEXTRA => SELF%F_PEXTRA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCLV)) SELF%PCLV => SELF%F_PCLV%GET_VIEW(BLOCK_INDEX)
    ! validation Fields 
    IF(ASSOCIATED(SELF%F_PCOVPTOT)) SELF%PCOVPTOT => SELF%F_PCOVPTOT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRAINFRAC_TOPRFZ)) SELF%PRAINFRAC_TOPRFZ => SELF%F_PRAINFRAC_TOPRFZ%GET_VIEW(BLOCK_INDEX)

  END SUBROUTINE AUX_TYPE_UPDATE_VIEW

  SUBROUTINE AUX_TYPE_SYNC_HOST(SELF)
    CLASS(CLOUDSC_AUX_TYPE) :: SELF
    ! Validation Fields 
    CALL SELF%F_PLUDE%SYNC_HOST_RDWR()
    CALL SELF%F_PCOVPTOT%SYNC_HOST_RDWR()
    CALL SELF%F_PRAINFRAC_TOPRFZ%SYNC_HOST_RDWR()
  END SUBROUTINE AUX_TYPE_SYNC_HOST

  SUBROUTINE AUX_TYPE_FINAL(SELF)
    CLASS(CLOUDSC_AUX_TYPE) :: SELF
    ! 2D Fields  
    CALL FIELD_DELETE(SELF%F_PLSM)
    CALL FIELD_DELETE(SELF%F_LDCUM)
    CALL FIELD_DELETE(SELF%F_KTYPE)
    ! 3D special fields
    CALL FIELD_DELETE(SELF%F_PLUDE)
    CALL FIELD_DELETE(SELF%F_PAPH)
    ! 4D Fields 
    CALL FIELD_DELETE(SELF%F_PEXTRA)
    CALL FIELD_DELETE(SELF%F_PCLV)
    ! Validation fields 
    CALL FIELD_DELETE(SELF%F_PCOVPTOT)
    CALL FIELD_DELETE(SELF%F_PRAINFRAC_TOPRFZ)
    ! 3D wronly fields
    IF(SELF%PACKED) THEN
      CALL FIELD_DELETE(SELF%DATA_RDONLY)
      DEALLOCATE(SELF%FIELDS_RDONLY)
    ELSE
      CALL FIELD_DELETE(SELF%F_PLCRIT_AER)
      CALL FIELD_DELETE(SELF%F_PICRIT_AER)
      CALL FIELD_DELETE(SELF%F_PRE_ICE)
      CALL FIELD_DELETE(SELF%F_PCCN)
      CALL FIELD_DELETE(SELF%F_PNICE)
      CALL FIELD_DELETE(SELF%F_PT)
      CALL FIELD_DELETE(SELF%F_PQ)
      CALL FIELD_DELETE(SELF%F_PVFA)
      CALL FIELD_DELETE(SELF%F_PVFL)
      CALL FIELD_DELETE(SELF%F_PVFI)
      CALL FIELD_DELETE(SELF%F_PDYNA)
      CALL FIELD_DELETE(SELF%F_PDYNL)
      CALL FIELD_DELETE(SELF%F_PDYNI)
      CALL FIELD_DELETE(SELF%F_PHRSW)
      CALL FIELD_DELETE(SELF%F_PHRLW)
      CALL FIELD_DELETE(SELF%F_PVERVEL)
      CALL FIELD_DELETE(SELF%F_PAP)
      CALL FIELD_DELETE(SELF%F_PLU)
      CALL FIELD_DELETE(SELF%F_PSNDE)
      CALL FIELD_DELETE(SELF%F_PMFU)
      CALL FIELD_DELETE(SELF%F_PMFD)
      CALL FIELD_DELETE(SELF%F_PA)
      CALL FIELD_DELETE(SELF%F_PSUPSAT)
    END IF
  END SUBROUTINE AUX_TYPE_FINAL

END MODULE CLOUDSC_AUX_TYPE_MOD
