SUBROUTINE routines
CHARACTER(LEN=*), PARAMETER :: CLPREFIX = 'ERROR: YOU SHOULD HAVE NEVER BE CALLING ROUTINE '
#include "abor1.intfb.h"
ENTRY DOTPROD2
CALL ABOR1(CLPREFIX//'DOTPROD2')
RETURN
ENTRY DOTPROD3
CALL ABOR1(CLPREFIX//'DOTPROD3')
RETURN
ENTRY VDIV
CALL ABOR1(CLPREFIX//'VDIV')
RETURN
ENTRY VEXP
CALL ABOR1(CLPREFIX//'VEXP')
RETURN
ENTRY VREC
CALL ABOR1(CLPREFIX//'VREC')
RETURN
ENTRY VPOW
CALL ABOR1(CLPREFIX//'VPOW')
RETURN
END SUBROUTINE routines
