MODULE YOECLDP

USE PARKIND1,    ONLY : JPIM, JPRB
USE FILE_IO_MOD, ONLY : LOAD_SCALAR, LOAD_ARRAY

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!     ** YOECLDP - CONTROL PARAMETERS FOR PROGNOSTIC CLOUD SCHEME
!     -----------------------------------------------------------------

!     * E.C.M.W.F. PHYSICS PACKAGE *

!     C. JAKOB     E.C.M.W.F.    94/02/07
!     A. Tompkins  E.C.M.W.F.  2004/12/03 total water variance setup for
!                                                  moist advection-diffusion PBL
!     A. Tompkins  E.C.M.W.F.  2004/09/02 Aerosol in microphysics switches
!     JJMorcrette  ECMWF       20100813   Aerosol index for aerosol-cloud interactions
!     R. Forbes    ECMWF       20110301   Added ice deposition parameters
!     R. Forbes    ECMWF       20150115   Added additional ice, snow and rain parameters

!      NAME     TYPE      PURPOSE
!      ----     ----      -------

!     *RAMID*   REAL      BASE VALUE FOR CALCULATION OF RELATIVE 
!                         HUMIDITY THRESHOLD FOR ONSET OF STRATIFORM
!                         CONDENSATION (TIEDTKE, 1993, EQUATION 24)
!     *RCLDIFF* REAL      DIFFUSION-COEFFICIENT FOR EVAPORATION BY
!                         TURBULENT MIXING (IBID., EQU. 30)
!     *RCLDIFF_CONVI*REAL ENHANCEMENT FACTOR OF  RCLDIFF FOR CONVECTION
!     *RCLCRIT* REAL      BASE VALUE OF CRITICAL CLOUD WATER CONTENT 
!                         FOR CONVERSION TO RAIN (SUNDQUIST, 1988)
!     *RCLCRIT_SEA* REAL  BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR SEA
!     *RCLCRIT_LAND* REAL BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR LAND
!     *RKCONV*  REAL      BASE VALUE FOR CONVERSION COEFFICIENT (IBID.)
!     *RPRC1*   REAL      COALESCENCE CONSTANT (IBID.)
!     *RPRC2*   REAL      BERGERON-FINDEISEN CONSTANT (IBID.)
!     *RCLDMAX* REAL      MAXIMUM CLOUD WATER CONTENT
!     *RPECONS* REAL      EVAPORATION CONSTANT AFTER KESSLER 
!                         (TIEDTKE, 1993, EQU.35)
!     *RPRECRHMAX* REAL   MAX THRESHOLD RH FOR EVAPORATION FOR ZERO COVER
!     *RTAUMEL* REAL      RELAXATION TIME FOR MELTING OF SNOW
!     *RAMIN*   REAL      LIMIT FOR A
!     *RLMIN*   REAL      LIMIT FOR L
!     *RKOOPTAU*  REAL    TIMESCALE FOR ICE SUPERSATURATION REMOVAL
!     *RVICE*     REAL    FIXED ICE FALLSPEED
!     *RVRAIN*    REAL    FIXED RAIN FALLSPEED
!     *RVSNOW*    REAL    FIXED SNOW FALLSPEED
!     *RTHOMO*    REAL    TEMPERATURE THRESHOLD FOR SPONTANEOUS FREEZING OF LIQUID DROPLETS
!     *RCOVPMIN*  REAL    MINIMUM PRECIPITATION COVERAGE REQUIRED FOR THE NEW PROGNOSTIC PRECIP
!     *RCLDTOPP*  REAL    TOP PRESSURE FOR CLOUD CALCULATION
!     *NCLDTOP*   INTEGER TOP LEVEL FOR CLOUD CALCULATION
!     *NSSOPT*  INTEGER   PARAMETRIZATION CHOICE FOR SUPERSATURATION
!     *NCLDDIAG*INTEGER   CONTROLS CLOUDSC DIAGNOSTICS IN PEXTRA
!     *NCLV*     INTEGER   NUMBER OF PROGNOSTIC EQUATIONS IN CLOUDSC 
!                         (INCLUDES WATER VAPOUR AS DUMMY VARIABLE) 
!      NAERCLD         INT  INDEX TO CONTROL SWITCHES FOR 
!                           AEROSOL-MICROPHYSICS INTERACTION, LAER*
!      NAECLxx         INT  INDEX OF GEMS AEROSOLS USED IN AEROSOL-CLOUD INTERACTIONS
!      RCCN            REAL DEFAULT CCN (CM-3)
!      RNICE           REAL DEFAULT ICE NUMBER CONCENTRATION (CM-3)
!      LAERLIQAUTOLSP  LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN LSP
!      LAERLIQAUTOCP   LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN CP
!      LAERLIQCOLL     LOG  AEROSOLS AFFECT RAIN COLLECTION 
!      LAERICESED      LOG  AEROSOLS AFFECT ICE SEDIMENTATION
!      LAERICEAUTO     LOG  AEROSOLS AFFECT ICE AUTOCONVERSION
!      RCCNOM          REAL CONSTANT IN MENON PARAM FOR ORGANIC MATTER -> CCN
!      RCCNSS          REAL CONSTANT IN MENON PARAM SEA SALT -> CCN
!      RCCNSU          REAL CONSTANT IN MENON PARAM FOR SULPHATE -> CCN
!      RCLDTOPCF       REAL Cloud fraction threshold that defines cloud top 
!      RDEPLIQREFRATE  REAL Fraction of deposition rate in cloud top layer
!      RDEPLIQREFDEPTH REAL Depth of supercooled liquid water layer (m)
!      RVRFACTOR       REAL KESSLER FACTOR=5.09E-3 FOR EVAPORATION OF CLEAR-SKY RAIN  (KESSLER,1969)

INTEGER(KIND=JPIM),PARAMETER :: NCLV=5      ! number of microphysics variables
INTEGER(KIND=JPIM),PARAMETER :: NCLDQL=1    ! liquid cloud water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQI=2    ! ice cloud water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQR=3    ! rain water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQS=4    ! snow
INTEGER(KIND=JPIM),PARAMETER :: NCLDQV=5    ! vapour

TYPE :: TECLDP
REAL(KIND=JPRB) :: RAMID
REAL(KIND=JPRB) :: RCLDIFF
REAL(KIND=JPRB) :: RCLDIFF_CONVI
REAL(KIND=JPRB) :: RCLCRIT
REAL(KIND=JPRB) :: RCLCRIT_SEA
REAL(KIND=JPRB) :: RCLCRIT_LAND
REAL(KIND=JPRB) :: RKCONV
REAL(KIND=JPRB) :: RPRC1
REAL(KIND=JPRB) :: RPRC2
REAL(KIND=JPRB) :: RCLDMAX
REAL(KIND=JPRB) :: RPECONS
REAL(KIND=JPRB) :: RVRFACTOR
REAL(KIND=JPRB) :: RPRECRHMAX
REAL(KIND=JPRB) :: RTAUMEL
REAL(KIND=JPRB) :: RAMIN
REAL(KIND=JPRB) :: RLMIN
REAL(KIND=JPRB) :: RKOOPTAU
REAL(KIND=JPRB) :: RCLDTOPP
REAL(KIND=JPRB) :: RLCRITSNOW
REAL(KIND=JPRB) :: RSNOWLIN1
REAL(KIND=JPRB) :: RSNOWLIN2
REAL(KIND=JPRB) :: RICEHI1
REAL(KIND=JPRB) :: RICEHI2
REAL(KIND=JPRB) :: RICEINIT
REAL(KIND=JPRB) :: RVICE
REAL(KIND=JPRB) :: RVRAIN
REAL(KIND=JPRB) :: RVSNOW
REAL(KIND=JPRB) :: RTHOMO
REAL(KIND=JPRB) :: RCOVPMIN
REAL(KIND=JPRB) :: RCCN
REAL(KIND=JPRB) :: RNICE
REAL(KIND=JPRB) :: RCCNOM
REAL(KIND=JPRB) :: RCCNSS
REAL(KIND=JPRB) :: RCCNSU
REAL(KIND=JPRB) :: RCLDTOPCF
REAL(KIND=JPRB) :: RDEPLIQREFRATE
REAL(KIND=JPRB) :: RDEPLIQREFDEPTH
!--------------------------------------------------------
! Autoconversion/accretion (Khairoutdinov and Kogan 2000)
!--------------------------------------------------------
REAL(KIND=JPRB) :: RCL_KKAac
REAL(KIND=JPRB) :: RCL_KKBac
REAL(KIND=JPRB) :: RCL_KKAau
REAL(KIND=JPRB) :: RCL_KKBauq
REAL(KIND=JPRB) :: RCL_KKBaun
REAL(KIND=JPRB) :: RCL_KK_cloud_num_sea
REAL(KIND=JPRB) :: RCL_KK_cloud_num_land
!--------------------------------------------------------
! Ice
!--------------------------------------------------------
REAL(KIND=JPRB) :: RCL_AI
REAL(KIND=JPRB) :: RCL_BI
REAL(KIND=JPRB) :: RCL_CI
REAL(KIND=JPRB) :: RCL_DI
REAL(KIND=JPRB) :: RCL_X1I
REAL(KIND=JPRB) :: RCL_X2I
REAL(KIND=JPRB) :: RCL_X3I
REAL(KIND=JPRB) :: RCL_X4I
REAL(KIND=JPRB) :: RCL_CONST1I
REAL(KIND=JPRB) :: RCL_CONST2I
REAL(KIND=JPRB) :: RCL_CONST3I
REAL(KIND=JPRB) :: RCL_CONST4I
REAL(KIND=JPRB) :: RCL_CONST5I
REAL(KIND=JPRB) :: RCL_CONST6I
REAL(KIND=JPRB) :: RCL_APB1
REAL(KIND=JPRB) :: RCL_APB2
REAL(KIND=JPRB) :: RCL_APB3
!--------------------------------------------------------
! Snow
!--------------------------------------------------------
REAL(KIND=JPRB) :: RCL_AS
REAL(KIND=JPRB) :: RCL_BS
REAL(KIND=JPRB) :: RCL_CS
REAL(KIND=JPRB) :: RCL_DS
REAL(KIND=JPRB) :: RCL_X1S
REAL(KIND=JPRB) :: RCL_X2S
REAL(KIND=JPRB) :: RCL_X3S
REAL(KIND=JPRB) :: RCL_X4S
REAL(KIND=JPRB) :: RCL_CONST1S
REAL(KIND=JPRB) :: RCL_CONST2S
REAL(KIND=JPRB) :: RCL_CONST3S
REAL(KIND=JPRB) :: RCL_CONST4S
REAL(KIND=JPRB) :: RCL_CONST5S
REAL(KIND=JPRB) :: RCL_CONST6S
REAL(KIND=JPRB) :: RCL_CONST7S
REAL(KIND=JPRB) :: RCL_CONST8S
!--------------------------------------------------------
! Rain
!--------------------------------------------------------
REAL(KIND=JPRB) :: RDENSWAT
REAL(KIND=JPRB) :: RDENSREF
REAL(KIND=JPRB) :: RCL_AR
REAL(KIND=JPRB) :: RCL_BR
REAL(KIND=JPRB) :: RCL_CR
REAL(KIND=JPRB) :: RCL_DR
REAL(KIND=JPRB) :: RCL_X1R
REAL(KIND=JPRB) :: RCL_X2R
REAL(KIND=JPRB) :: RCL_X4R
REAL(KIND=JPRB) :: RCL_KA273
REAL(KIND=JPRB) :: RCL_CDENOM1
REAL(KIND=JPRB) :: RCL_CDENOM2
REAL(KIND=JPRB) :: RCL_CDENOM3
REAL(KIND=JPRB) :: RCL_SCHMIDT
REAL(KIND=JPRB) :: RCL_DYNVISC
REAL(KIND=JPRB) :: RCL_CONST1R
REAL(KIND=JPRB) :: RCL_CONST2R
REAL(KIND=JPRB) :: RCL_CONST3R
REAL(KIND=JPRB) :: RCL_CONST4R
REAL(KIND=JPRB) :: RCL_FAC1
REAL(KIND=JPRB) :: RCL_FAC2
! Rain freezing
REAL(KIND=JPRB) :: RCL_CONST5R
REAL(KIND=JPRB) :: RCL_CONST6R
REAL(KIND=JPRB) :: RCL_FZRAB
REAL(KIND=JPRB) :: RCL_FZRBB

LOGICAL :: LCLDEXTRA, LCLDBUDGET

INTEGER(KIND=JPIM) :: NSSOPT
INTEGER(KIND=JPIM) :: NCLDTOP
INTEGER(KIND=JPIM) :: NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU
INTEGER(KIND=JPIM) :: NCLDDIAG

! aerosols
INTEGER(KIND=JPIM) :: NAERCLD
LOGICAL :: LAERLIQAUTOLSP
LOGICAL :: LAERLIQAUTOCP
LOGICAL :: LAERLIQAUTOCPB
LOGICAL :: LAERLIQCOLL
LOGICAL :: LAERICESED
LOGICAL :: LAERICEAUTO

! variance arrays
REAL(KIND=JPRB) :: NSHAPEP
REAL(KIND=JPRB) :: NSHAPEQ
INTEGER(KIND=JPIM) :: NBETA
REAL(KIND=JPRB) :: RBETA(0:100)
REAL(KIND=JPRB) :: RBETAP1(0:100)


END TYPE TECLDP

TYPE(TECLDP), ALLOCATABLE :: YRECLDP

!$acc declare copyin(yrecldp)

CONTAINS

  SUBROUTINE YRECLDP_LOAD_PARAMETERS()
    ALLOCATE(YRECLDP)
    CALL LOAD_SCALAR('YRECLDP_RAMID', YRECLDP%RAMID)
    CALL LOAD_SCALAR('YRECLDP_RCLDIFF', YRECLDP%RCLDIFF)
    CALL LOAD_SCALAR('YRECLDP_RCLDIFF_CONVI', YRECLDP%RCLDIFF_CONVI)
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT', YRECLDP%RCLCRIT)
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT_SEA', YRECLDP%RCLCRIT_SEA)
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT_LAND', YRECLDP%RCLCRIT_LAND)
    CALL LOAD_SCALAR('YRECLDP_RKCONV', YRECLDP%RKCONV)
    CALL LOAD_SCALAR('YRECLDP_RPRC1', YRECLDP%RPRC1)
    CALL LOAD_SCALAR('YRECLDP_RPRC2', YRECLDP%RPRC2)
    CALL LOAD_SCALAR('YRECLDP_RCLDMAX', YRECLDP%RCLDMAX)
    CALL LOAD_SCALAR('YRECLDP_RPECONS', YRECLDP%RPECONS)
    CALL LOAD_SCALAR('YRECLDP_RVRFACTOR', YRECLDP%RVRFACTOR)
    CALL LOAD_SCALAR('YRECLDP_RPRECRHMAX', YRECLDP%RPRECRHMAX)
    CALL LOAD_SCALAR('YRECLDP_RTAUMEL', YRECLDP%RTAUMEL)
    CALL LOAD_SCALAR('YRECLDP_RAMIN', YRECLDP%RAMIN)
    CALL LOAD_SCALAR('YRECLDP_RLMIN', YRECLDP%RLMIN)
    CALL LOAD_SCALAR('YRECLDP_RKOOPTAU', YRECLDP%RKOOPTAU)

    CALL LOAD_SCALAR('YRECLDP_RCLDTOPP', YRECLDP%RCLDTOPP)
    CALL LOAD_SCALAR('YRECLDP_RLCRITSNOW', YRECLDP%RLCRITSNOW)
    CALL LOAD_SCALAR('YRECLDP_RSNOWLIN1', YRECLDP%RSNOWLIN1)
    CALL LOAD_SCALAR('YRECLDP_RSNOWLIN2', YRECLDP%RSNOWLIN2)
    CALL LOAD_SCALAR('YRECLDP_RICEHI1', YRECLDP%RICEHI1)
    CALL LOAD_SCALAR('YRECLDP_RICEHI2', YRECLDP%RICEHI2)
    CALL LOAD_SCALAR('YRECLDP_RICEINIT', YRECLDP%RICEINIT)
    CALL LOAD_SCALAR('YRECLDP_RVICE', YRECLDP%RVICE)
    CALL LOAD_SCALAR('YRECLDP_RVRAIN', YRECLDP%RVRAIN)
    CALL LOAD_SCALAR('YRECLDP_RVSNOW', YRECLDP%RVSNOW)
    CALL LOAD_SCALAR('YRECLDP_RTHOMO', YRECLDP%RTHOMO)
    CALL LOAD_SCALAR('YRECLDP_RCOVPMIN', YRECLDP%RCOVPMIN)
    CALL LOAD_SCALAR('YRECLDP_RCCN', YRECLDP%RCCN)
    CALL LOAD_SCALAR('YRECLDP_RNICE', YRECLDP%RNICE)
    CALL LOAD_SCALAR('YRECLDP_RCCNOM', YRECLDP%RCCNOM)
    CALL LOAD_SCALAR('YRECLDP_RCCNSS', YRECLDP%RCCNSS)
    CALL LOAD_SCALAR('YRECLDP_RCCNSU', YRECLDP%RCCNSU)
    CALL LOAD_SCALAR('YRECLDP_RCLDTOPCF', YRECLDP%RCLDTOPCF)
    CALL LOAD_SCALAR('YRECLDP_RDEPLIQREFRATE', YRECLDP%RDEPLIQREFRATE)
    CALL LOAD_SCALAR('YRECLDP_RDEPLIQREFDEPTH', YRECLDP%RDEPLIQREFDEPTH)
    CALL LOAD_SCALAR('YRECLDP_RCL_KKAac', YRECLDP%RCL_KKAac)
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBac', YRECLDP%RCL_KKBac)
    CALL LOAD_SCALAR('YRECLDP_RCL_KKAau', YRECLDP%RCL_KKAau)
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBauq', YRECLDP%RCL_KKBauq)
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBaun', YRECLDP%RCL_KKBaun)
    CALL LOAD_SCALAR('YRECLDP_RCL_KK_cloud_num_sea', YRECLDP%RCL_KK_cloud_num_sea)
    CALL LOAD_SCALAR('YRECLDP_RCL_KK_cloud_num_land', YRECLDP%RCL_KK_cloud_num_land)
    CALL LOAD_SCALAR('YRECLDP_RCL_AI', YRECLDP%RCL_AI)
    CALL LOAD_SCALAR('YRECLDP_RCL_BI', YRECLDP%RCL_BI)
    CALL LOAD_SCALAR('YRECLDP_RCL_CI', YRECLDP%RCL_CI)
    CALL LOAD_SCALAR('YRECLDP_RCL_DI', YRECLDP%RCL_DI)
    CALL LOAD_SCALAR('YRECLDP_RCL_X1I', YRECLDP%RCL_X1I)
    CALL LOAD_SCALAR('YRECLDP_RCL_X2I', YRECLDP%RCL_X2I)
    CALL LOAD_SCALAR('YRECLDP_RCL_X3I', YRECLDP%RCL_X3I)
    CALL LOAD_SCALAR('YRECLDP_RCL_X4I', YRECLDP%RCL_X4I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1I', YRECLDP%RCL_CONST1I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2I', YRECLDP%RCL_CONST2I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3I', YRECLDP%RCL_CONST3I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4I', YRECLDP%RCL_CONST4I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5I', YRECLDP%RCL_CONST5I)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6I', YRECLDP%RCL_CONST6I)
    CALL LOAD_SCALAR('YRECLDP_RCL_APB1', YRECLDP%RCL_APB1)
    CALL LOAD_SCALAR('YRECLDP_RCL_APB2', YRECLDP%RCL_APB2)
    CALL LOAD_SCALAR('YRECLDP_RCL_APB3', YRECLDP%RCL_APB3)
    CALL LOAD_SCALAR('YRECLDP_RCL_AS', YRECLDP%RCL_AS)
    CALL LOAD_SCALAR('YRECLDP_RCL_BS', YRECLDP%RCL_BS)
    CALL LOAD_SCALAR('YRECLDP_RCL_CS', YRECLDP%RCL_CS)
    CALL LOAD_SCALAR('YRECLDP_RCL_DS', YRECLDP%RCL_DS)
    CALL LOAD_SCALAR('YRECLDP_RCL_X1S', YRECLDP%RCL_X1S)
    CALL LOAD_SCALAR('YRECLDP_RCL_X2S', YRECLDP%RCL_X2S)
    CALL LOAD_SCALAR('YRECLDP_RCL_X3S', YRECLDP%RCL_X3S)
    CALL LOAD_SCALAR('YRECLDP_RCL_X4S', YRECLDP%RCL_X4S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1S', YRECLDP%RCL_CONST1S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2S', YRECLDP%RCL_CONST2S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3S', YRECLDP%RCL_CONST3S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4S', YRECLDP%RCL_CONST4S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5S', YRECLDP%RCL_CONST5S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6S', YRECLDP%RCL_CONST6S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST7S', YRECLDP%RCL_CONST7S)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST8S', YRECLDP%RCL_CONST8S)
    CALL LOAD_SCALAR('YRECLDP_RDENSWAT', YRECLDP%RDENSWAT)
    CALL LOAD_SCALAR('YRECLDP_RDENSREF', YRECLDP%RDENSREF)
    CALL LOAD_SCALAR('YRECLDP_RCL_AR', YRECLDP%RCL_AR)
    CALL LOAD_SCALAR('YRECLDP_RCL_BR', YRECLDP%RCL_BR)
    CALL LOAD_SCALAR('YRECLDP_RCL_CR', YRECLDP%RCL_CR)
    CALL LOAD_SCALAR('YRECLDP_RCL_DR', YRECLDP%RCL_DR)
    CALL LOAD_SCALAR('YRECLDP_RCL_X1R', YRECLDP%RCL_X1R)
    CALL LOAD_SCALAR('YRECLDP_RCL_X2R', YRECLDP%RCL_X2R)
    CALL LOAD_SCALAR('YRECLDP_RCL_X4R', YRECLDP%RCL_X4R)
    CALL LOAD_SCALAR('YRECLDP_RCL_KA273', YRECLDP%RCL_KA273)
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM1', YRECLDP%RCL_CDENOM1)
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM2', YRECLDP%RCL_CDENOM2)
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM3', YRECLDP%RCL_CDENOM3)
    CALL LOAD_SCALAR('YRECLDP_RCL_SCHMIDT', YRECLDP%RCL_SCHMIDT)
    CALL LOAD_SCALAR('YRECLDP_RCL_DYNVISC', YRECLDP%RCL_DYNVISC)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1R', YRECLDP%RCL_CONST1R)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2R', YRECLDP%RCL_CONST2R)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3R', YRECLDP%RCL_CONST3R)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4R', YRECLDP%RCL_CONST4R)
    CALL LOAD_SCALAR('YRECLDP_RCL_FAC1', YRECLDP%RCL_FAC1)
    CALL LOAD_SCALAR('YRECLDP_RCL_FAC2', YRECLDP%RCL_FAC2)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5R', YRECLDP%RCL_CONST5R)
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6R', YRECLDP%RCL_CONST6R)
    CALL LOAD_SCALAR('YRECLDP_RCL_FZRAB', YRECLDP%RCL_FZRAB)
    CALL LOAD_SCALAR('YRECLDP_RCL_FZRBB', YRECLDP%RCL_FZRBB)
    CALL LOAD_SCALAR('YRECLDP_LCLDEXTRA', YRECLDP%LCLDEXTRA)
    CALL LOAD_SCALAR('YRECLDP_LCLDBUDGET', YRECLDP%LCLDBUDGET)
    CALL LOAD_SCALAR('YRECLDP_NSSOPT', YRECLDP%NSSOPT)
    CALL LOAD_SCALAR('YRECLDP_NCLDTOP', YRECLDP%NCLDTOP)
    CALL LOAD_SCALAR('YRECLDP_NAECLBC', YRECLDP%NAECLBC)
    CALL LOAD_SCALAR('YRECLDP_NAECLDU', YRECLDP%NAECLDU)
    CALL LOAD_SCALAR('YRECLDP_NAECLOM', YRECLDP%NAECLOM)
    CALL LOAD_SCALAR('YRECLDP_NAECLSS', YRECLDP%NAECLSS)
    CALL LOAD_SCALAR('YRECLDP_NAECLSU', YRECLDP%NAECLSU)
    CALL LOAD_SCALAR('YRECLDP_NCLDDIAG', YRECLDP%NCLDDIAG)
    CALL LOAD_SCALAR('YRECLDP_NAERCLD', YRECLDP%NAERCLD)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOLSP', YRECLDP%LAERLIQAUTOLSP)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOCP', YRECLDP%LAERLIQAUTOCP)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOCPB', YRECLDP%LAERLIQAUTOCPB)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQCOLL', YRECLDP%LAERLIQCOLL)
    CALL LOAD_SCALAR('YRECLDP_LAERICESED', YRECLDP%LAERICESED)
    CALL LOAD_SCALAR('YRECLDP_LAERICEAUTO', YRECLDP%LAERICEAUTO)
    CALL LOAD_SCALAR('YRECLDP_NSHAPEP', YRECLDP%NSHAPEP)
    CALL LOAD_SCALAR('YRECLDP_NSHAPEQ', YRECLDP%NSHAPEQ)
    CALL LOAD_SCALAR('YRECLDP_NBETA', YRECLDP%NBETA)
    ! The last two are actually arrays, so treat them as fields
    CALL LOAD_ARRAY('YRECLDP_RBETA', 1, 101, 101, 101, YRECLDP%RBETA(0:100))
    CALL LOAD_ARRAY('YRECLDP_RBETAP1', 1, 101, 101, 101, YRECLDP%RBETAP1(0:100))
  END SUBROUTINE YRECLDP_LOAD_PARAMETERS

END MODULE YOECLDP
