! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE YOECLDP_CUF

USE PARKIND1,    ONLY : JPIM, JPRB
USE YOECLDP,     ONLY : YRECLDP

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!     ** YOECLDP - CONTROL PARAMETERS FOR PROGNOSTIC CLOUD SCHEME
!     -----------------------------------------------------------------

!     * E.C.M.W.F. PHYSICS PACKAGE *

!     C. JAKOB     E.C.M.W.F.    94/02/07
!     A. Tompkins  E.C.M.W.F.  2004/12/03 total water variance setup for
!                                                  moist advection-diffusion PBL
!     A. Tompkins  E.C.M.W.F.  2004/09/02 Aerosol in microphysics switches
!     JJMorcrette  ECMWF       20100813   Aerosol index for aerosol-cloud interactions
!     R. Forbes    ECMWF       20110301   Added ice deposition parameters
!     R. Forbes    ECMWF       20150115   Added additional ice, snow and rain parameters

!      NAME     TYPE      PURPOSE
!      ----     ----      -------

!     *RAMID*   REAL      BASE VALUE FOR CALCULATION OF RELATIVE 
!                         HUMIDITY THRESHOLD FOR ONSET OF STRATIFORM
!                         CONDENSATION (TIEDTKE, 1993, EQUATION 24)
!     *RCLDIFF* REAL      DIFFUSION-COEFFICIENT FOR EVAPORATION BY
!                         TURBULENT MIXING (IBID., EQU. 30)
!     *RCLDIFF_CONVI*REAL ENHANCEMENT FACTOR OF  RCLDIFF FOR CONVECTION
!     *RCLCRIT* REAL      BASE VALUE OF CRITICAL CLOUD WATER CONTENT 
!                         FOR CONVERSION TO RAIN (SUNDQUIST, 1988)
!     *RCLCRIT_SEA* REAL  BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR SEA
!     *RCLCRIT_LAND* REAL BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR LAND
!     *RKCONV*  REAL      BASE VALUE FOR CONVERSION COEFFICIENT (IBID.)
!     *RPRC1*   REAL      COALESCENCE CONSTANT (IBID.)
!     *RPRC2*   REAL      BERGERON-FINDEISEN CONSTANT (IBID.)
!     *RCLDMAX* REAL      MAXIMUM CLOUD WATER CONTENT
!     *RPECONS* REAL      EVAPORATION CONSTANT AFTER KESSLER 
!                         (TIEDTKE, 1993, EQU.35)
!     *RPRECRHMAX* REAL   MAX THRESHOLD RH FOR EVAPORATION FOR ZERO COVER
!     *RTAUMEL* REAL      RELAXATION TIME FOR MELTING OF SNOW
!     *RAMIN*   REAL      LIMIT FOR A
!     *RLMIN*   REAL      LIMIT FOR L
!     *RKOOPTAU*  REAL    TIMESCALE FOR ICE SUPERSATURATION REMOVAL
!     *RVICE*     REAL    FIXED ICE FALLSPEED
!     *RVRAIN*    REAL    FIXED RAIN FALLSPEED
!     *RVSNOW*    REAL    FIXED SNOW FALLSPEED
!     *RTHOMO*    REAL    TEMPERATURE THRESHOLD FOR SPONTANEOUS FREEZING OF LIQUID DROPLETS
!     *RCOVPMIN*  REAL    MINIMUM PRECIPITATION COVERAGE REQUIRED FOR THE NEW PROGNOSTIC PRECIP
!     *RCLDTOPP*  REAL    TOP PRESSURE FOR CLOUD CALCULATION
!     *NCLDTOP*   INTEGER TOP LEVEL FOR CLOUD CALCULATION
!     *NSSOPT*  INTEGER   PARAMETRIZATION CHOICE FOR SUPERSATURATION
!     *NCLDDIAG*INTEGER   CONTROLS CLOUDSC DIAGNOSTICS IN PEXTRA
!     *NCLV*     INTEGER   NUMBER OF PROGNOSTIC EQUATIONS IN CLOUDSC 
!                         (INCLUDES WATER VAPOUR AS DUMMY VARIABLE) 
!      NAERCLD         INT  INDEX TO CONTROL SWITCHES FOR 
!                           AEROSOL-MICROPHYSICS INTERACTION, LAER*
!      NAECLxx         INT  INDEX OF GEMS AEROSOLS USED IN AEROSOL-CLOUD INTERACTIONS
!      RCCN            REAL DEFAULT CCN (CM-3)
!      RNICE           REAL DEFAULT ICE NUMBER CONCENTRATION (CM-3)
!      LAERLIQAUTOLSP  LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN LSP
!      LAERLIQAUTOCP   LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN CP
!      LAERLIQCOLL     LOG  AEROSOLS AFFECT RAIN COLLECTION 
!      LAERICESED      LOG  AEROSOLS AFFECT ICE SEDIMENTATION
!      LAERICEAUTO     LOG  AEROSOLS AFFECT ICE AUTOCONVERSION
!      RCCNOM          REAL CONSTANT IN MENON PARAM FOR ORGANIC MATTER -> CCN
!      RCCNSS          REAL CONSTANT IN MENON PARAM SEA SALT -> CCN
!      RCCNSU          REAL CONSTANT IN MENON PARAM FOR SULPHATE -> CCN
!      RCLDTOPCF       REAL Cloud fraction threshold that defines cloud top 
!      RDEPLIQREFRATE  REAL Fraction of deposition rate in cloud top layer
!      RDEPLIQREFDEPTH REAL Depth of supercooled liquid water layer (m)
!      RVRFACTOR       REAL KESSLER FACTOR=5.09E-3 FOR EVAPORATION OF CLEAR-SKY RAIN  (KESSLER,1969)

!! GPU-constant version
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RAMID
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLDIFF
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLDIFF_CONVI
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLCRIT
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLCRIT_SEA
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLCRIT_LAND
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RKCONV
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RPRC1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RPRC2
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLDMAX
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RPECONS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RVRFACTOR
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RPRECRHMAX
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RTAUMEL
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RAMIN
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RLMIN
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RKOOPTAU
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLDTOPP
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RLCRITSNOW
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RSNOWLIN1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RSNOWLIN2
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RICEHI1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RICEHI2
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RICEINIT
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RVICE
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RVRAIN
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RVSNOW
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RTHOMO
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCOVPMIN
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCCN
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RNICE
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCCNOM
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCCNSS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCCNSU
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCLDTOPCF
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RDEPLIQREFRATE
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RDEPLIQREFDEPTH
!--------------------------------------------------------
! Autoconversion/accretion (Khairoutdinov and Kogan 2000)
!--------------------------------------------------------
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KKAac
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KKBac
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KKAau
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KKBauq
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KKBaun
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KK_cloud_num_sea
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KK_cloud_num_land
!--------------------------------------------------------
! Ice
!--------------------------------------------------------
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_AI
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_BI
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CI
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_DI
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X1I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X2I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X3I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X4I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST1I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST2I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST3I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST4I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST5I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST6I
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_APB1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_APB2
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_APB3
!--------------------------------------------------------
! Snow
!--------------------------------------------------------
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_AS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_BS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_DS
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X1S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X2S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X3S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X4S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST1S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST2S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST3S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST4S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST5S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST6S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST7S
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST8S
!--------------------------------------------------------
! Rain
!--------------------------------------------------------
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RDENSWAT
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RDENSREF
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_AR
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_BR
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CR
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_DR
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X1R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X2R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_X4R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_KA273
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CDENOM1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CDENOM2
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CDENOM3
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_SCHMIDT
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_DYNVISC
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST1R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST2R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST3R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST4R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_FAC1
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_FAC2
! Rain freezing
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST5R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_CONST6R
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_FZRAB
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RCL_FZRBB

LOGICAL, CONSTANT :: YRECLDP_LCLDEXTRA, YRECLDP_LCLDBUDGET

INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NSSOPT
INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NCLDTOP
INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NAECLBC, YRECLDP_NAECLDU, YRECLDP_NAECLOM, YRECLDP_NAECLSS, YRECLDP_NAECLSU
INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NCLDDIAG

! aerosols
INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NAERCLD
LOGICAL, CONSTANT :: YRECLDP_LAERLIQAUTOLSP
LOGICAL, CONSTANT :: YRECLDP_LAERLIQAUTOCP
LOGICAL, CONSTANT :: YRECLDP_LAERLIQAUTOCPB
LOGICAL, CONSTANT :: YRECLDP_LAERLIQCOLL
LOGICAL, CONSTANT :: YRECLDP_LAERICESED
LOGICAL, CONSTANT :: YRECLDP_LAERICEAUTO

! variance arrays
REAL(KIND=JPRB), CONSTANT :: YRECLDP_NSHAPEP
REAL(KIND=JPRB), CONSTANT :: YRECLDP_NSHAPEQ
INTEGER(KIND=JPIM), CONSTANT :: YRECLDP_NBETA
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RBETA(0:100)
REAL(KIND=JPRB), CONSTANT :: YRECLDP_RBETAP1(0:100)


CONTAINS

  ATTRIBUTES(HOST) SUBROUTINE YRECLDP_UPDATE_DEVICE()

    YRECLDP_RAMID = YRECLDP%RAMID
    YRECLDP_RCLDIFF = YRECLDP%RCLDIFF
    YRECLDP_RCLDIFF_CONVI = YRECLDP%RCLDIFF_CONVI
    YRECLDP_RCLCRIT = YRECLDP%RCLCRIT
    YRECLDP_RCLCRIT_SEA = YRECLDP%RCLCRIT_SEA
    YRECLDP_RCLCRIT_LAND = YRECLDP%RCLCRIT_LAND
    YRECLDP_RKCONV = YRECLDP%RKCONV
    YRECLDP_RPRC1 = YRECLDP%RPRC1
    YRECLDP_RPRC2 = YRECLDP%RPRC2
    YRECLDP_RCLDMAX = YRECLDP%RCLDMAX
    YRECLDP_RPECONS = YRECLDP%RPECONS
    YRECLDP_RVRFACTOR = YRECLDP%RVRFACTOR
    YRECLDP_RPRECRHMAX = YRECLDP%RPRECRHMAX
    YRECLDP_RTAUMEL = YRECLDP%RTAUMEL
    YRECLDP_RAMIN = YRECLDP%RAMIN
    YRECLDP_RLMIN = YRECLDP%RLMIN
    YRECLDP_RKOOPTAU = YRECLDP%RKOOPTAU

    YRECLDP_RCLDTOPP = YRECLDP%RCLDTOPP
    YRECLDP_RLCRITSNOW = YRECLDP%RLCRITSNOW
    YRECLDP_RSNOWLIN1 = YRECLDP%RSNOWLIN1
    YRECLDP_RSNOWLIN2 = YRECLDP%RSNOWLIN2
    YRECLDP_RICEHI1 = YRECLDP%RICEHI1
    YRECLDP_RICEHI2 = YRECLDP%RICEHI2
    YRECLDP_RICEINIT = YRECLDP%RICEINIT
    YRECLDP_RVICE = YRECLDP%RVICE
    YRECLDP_RVRAIN = YRECLDP%RVRAIN
    YRECLDP_RVSNOW = YRECLDP%RVSNOW
    YRECLDP_RTHOMO = YRECLDP%RTHOMO
    YRECLDP_RCOVPMIN = YRECLDP%RCOVPMIN
    YRECLDP_RCCN = YRECLDP%RCCN
    YRECLDP_RNICE = YRECLDP%RNICE
    YRECLDP_RCCNOM = YRECLDP%RCCNOM
    YRECLDP_RCCNSS = YRECLDP%RCCNSS
    YRECLDP_RCCNSU = YRECLDP%RCCNSU
    YRECLDP_RCLDTOPCF = YRECLDP%RCLDTOPCF
    YRECLDP_RDEPLIQREFRATE = YRECLDP%RDEPLIQREFRATE
    YRECLDP_RDEPLIQREFDEPTH = YRECLDP%RDEPLIQREFDEPTH
    YRECLDP_RCL_KKAac = YRECLDP%RCL_KKAac
    YRECLDP_RCL_KKBac = YRECLDP%RCL_KKBac
    YRECLDP_RCL_KKAau = YRECLDP%RCL_KKAau
    YRECLDP_RCL_KKBauq = YRECLDP%RCL_KKBauq
    YRECLDP_RCL_KKBaun = YRECLDP%RCL_KKBaun
    YRECLDP_RCL_KK_cloud_num_sea = YRECLDP%RCL_KK_cloud_num_sea
    YRECLDP_RCL_KK_cloud_num_land = YRECLDP%RCL_KK_cloud_num_land
    YRECLDP_RCL_AI = YRECLDP%RCL_AI
    YRECLDP_RCL_BI = YRECLDP%RCL_BI
    YRECLDP_RCL_CI = YRECLDP%RCL_CI
    YRECLDP_RCL_DI = YRECLDP%RCL_DI
    YRECLDP_RCL_X1I = YRECLDP%RCL_X1I
    YRECLDP_RCL_X2I = YRECLDP%RCL_X2I
    YRECLDP_RCL_X3I = YRECLDP%RCL_X3I
    YRECLDP_RCL_X4I = YRECLDP%RCL_X4I
    YRECLDP_RCL_CONST1I = YRECLDP%RCL_CONST1I
    YRECLDP_RCL_CONST2I = YRECLDP%RCL_CONST2I
    YRECLDP_RCL_CONST3I = YRECLDP%RCL_CONST3I
    YRECLDP_RCL_CONST4I = YRECLDP%RCL_CONST4I
    YRECLDP_RCL_CONST5I = YRECLDP%RCL_CONST5I
    YRECLDP_RCL_CONST6I = YRECLDP%RCL_CONST6I
    YRECLDP_RCL_APB1 = YRECLDP%RCL_APB1
    YRECLDP_RCL_APB2 = YRECLDP%RCL_APB2
    YRECLDP_RCL_APB3 = YRECLDP%RCL_APB3
    YRECLDP_RCL_AS = YRECLDP%RCL_AS
    YRECLDP_RCL_BS = YRECLDP%RCL_BS
    YRECLDP_RCL_CS = YRECLDP%RCL_CS
    YRECLDP_RCL_DS = YRECLDP%RCL_DS
    YRECLDP_RCL_X1S = YRECLDP%RCL_X1S
    YRECLDP_RCL_X2S = YRECLDP%RCL_X2S
    YRECLDP_RCL_X3S = YRECLDP%RCL_X3S
    YRECLDP_RCL_X4S = YRECLDP%RCL_X4S
    YRECLDP_RCL_CONST1S = YRECLDP%RCL_CONST1S
    YRECLDP_RCL_CONST2S = YRECLDP%RCL_CONST2S
    YRECLDP_RCL_CONST3S = YRECLDP%RCL_CONST3S
    YRECLDP_RCL_CONST4S = YRECLDP%RCL_CONST4S
    YRECLDP_RCL_CONST5S = YRECLDP%RCL_CONST5S
    YRECLDP_RCL_CONST6S = YRECLDP%RCL_CONST6S
    YRECLDP_RCL_CONST7S = YRECLDP%RCL_CONST7S
    YRECLDP_RCL_CONST8S = YRECLDP%RCL_CONST8S
    YRECLDP_RDENSWAT = YRECLDP%RDENSWAT
    YRECLDP_RDENSREF = YRECLDP%RDENSREF
    YRECLDP_RCL_AR = YRECLDP%RCL_AR
    YRECLDP_RCL_BR = YRECLDP%RCL_BR
    YRECLDP_RCL_CR = YRECLDP%RCL_CR
    YRECLDP_RCL_DR = YRECLDP%RCL_DR
    YRECLDP_RCL_X1R = YRECLDP%RCL_X1R
    YRECLDP_RCL_X2R = YRECLDP%RCL_X2R
    YRECLDP_RCL_X4R = YRECLDP%RCL_X4R
    YRECLDP_RCL_KA273 = YRECLDP%RCL_KA273
    YRECLDP_RCL_CDENOM1 = YRECLDP%RCL_CDENOM1
    YRECLDP_RCL_CDENOM2 = YRECLDP%RCL_CDENOM2
    YRECLDP_RCL_CDENOM3 = YRECLDP%RCL_CDENOM3
    YRECLDP_RCL_SCHMIDT = YRECLDP%RCL_SCHMIDT
    YRECLDP_RCL_DYNVISC = YRECLDP%RCL_DYNVISC
    YRECLDP_RCL_CONST1R = YRECLDP%RCL_CONST1R
    YRECLDP_RCL_CONST2R = YRECLDP%RCL_CONST2R
    YRECLDP_RCL_CONST3R = YRECLDP%RCL_CONST3R
    YRECLDP_RCL_CONST4R = YRECLDP%RCL_CONST4R
    YRECLDP_RCL_FAC1 = YRECLDP%RCL_FAC1
    YRECLDP_RCL_FAC2 = YRECLDP%RCL_FAC2
    YRECLDP_RCL_CONST5R = YRECLDP%RCL_CONST5R
    YRECLDP_RCL_CONST6R = YRECLDP%RCL_CONST6R
    YRECLDP_RCL_FZRAB = YRECLDP%RCL_FZRAB
    YRECLDP_RCL_FZRBB = YRECLDP%RCL_FZRBB
    YRECLDP_LCLDEXTRA = YRECLDP%LCLDEXTRA
    YRECLDP_LCLDBUDGET = YRECLDP%LCLDBUDGET
    YRECLDP_NSSOPT = YRECLDP%NSSOPT
    YRECLDP_NCLDTOP = YRECLDP%NCLDTOP
    YRECLDP_NAECLBC = YRECLDP%NAECLBC
    YRECLDP_NAECLDU = YRECLDP%NAECLDU
    YRECLDP_NAECLOM = YRECLDP%NAECLOM
    YRECLDP_NAECLSS = YRECLDP%NAECLSS
    YRECLDP_NAECLSU = YRECLDP%NAECLSU
    YRECLDP_NCLDDIAG = YRECLDP%NCLDDIAG
    YRECLDP_NAERCLD = YRECLDP%NAERCLD
    YRECLDP_LAERLIQAUTOLSP = YRECLDP%LAERLIQAUTOLSP
    YRECLDP_LAERLIQAUTOCP = YRECLDP%LAERLIQAUTOCP
    YRECLDP_LAERLIQAUTOCPB = YRECLDP%LAERLIQAUTOCPB
    YRECLDP_LAERLIQCOLL = YRECLDP%LAERLIQCOLL
    YRECLDP_LAERICESED = YRECLDP%LAERICESED
    YRECLDP_LAERICEAUTO = YRECLDP%LAERICEAUTO
    YRECLDP_NSHAPEP = YRECLDP%NSHAPEP
    YRECLDP_NSHAPEQ = YRECLDP%NSHAPEQ
    YRECLDP_NBETA = YRECLDP%NBETA
    ! The last two are actually arrays, so treat them as fields
    YRECLDP_RBETA = YRECLDP%RBETA(0:100)
    YRECLDP_RBETAP1 = YRECLDP%RBETAP1(0:100)

  END SUBROUTINE YRECLDP_UPDATE_DEVICE

END MODULE YOECLDP_CUF

