MODULE YOEPHLI

USE PARKIND1,    ONLY : JPRB
USE FILE_IO_MOD, ONLY : LOAD_SCALAR

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!*    ** *YOEPHLI* CONTAINS CONSTANTS FOR THE LINEARIZED PHYSICS
!     ------------------------------------------------------------------

TYPE :: TEPHLI
LOGICAL :: LTLEVOL
LOGICAL :: LPHYLIN
LOGICAL :: LENOPERT
LOGICAL :: LEPPCFLS
LOGICAL :: LRAISANEN

REAL(KIND=JPRB) :: RLPTRC
REAL(KIND=JPRB) :: RLPAL1
REAL(KIND=JPRB) :: RLPAL2
REAL(KIND=JPRB) :: RLPBB
REAL(KIND=JPRB) :: RLPCC
REAL(KIND=JPRB) :: RLPDD
REAL(KIND=JPRB) :: RLPMIXL
REAL(KIND=JPRB) :: RLPBETA
REAL(KIND=JPRB) :: RLPDRAG
REAL(KIND=JPRB) :: RLPEVAP
REAL(KIND=JPRB) :: RLPP00
END TYPE TEPHLI

TYPE(TEPHLI), POINTER :: YREPHLI => NULL()



!*     *YOEPHLI* CONTAINS CONSTANTS NEEDED BY 
!     THE LINEARIZED PHYSICS

!     J.F. MAHFOUF        E.C.M.W.F.    23/06/96

!     NAME        TYPE     DESCRIPTION
!     ----        ----     -----------

!     *RLPTRC*    REAL     CRITICAL TEMPERATURE FOR MIXED PHASE PROPERTIES
!                          OF WATER 
!     *RLPAL1*    REAL     SMOOTHING COEFFICIENT
!     *RLPAL2*    REAL     SMOOTHING COEFFICIENT
!     *RLPBB*     REAL     CONSTANT FROM THE LOUIS ET AL. FORMULATION
!     *RLPCC*     REAL     CONSTANT FROM THE LOUIS ET AL. FORMULATION
!     *RLPDD*     REAL     CONSTANT FROM THE LOUIS ET AL. FORMULATION
!     *RLPMIXL*   REAL     PSEUDO DEPTH OF THE PLANETARY BOUNDARY LAYER
!     *RLPBETA*   REAL     REDUCTION FACTOR OF THE ASYMPTOTIC MIXING LENGTH
!     *RLPDRAG*   REAL     COEFFICIENT FOR THE ESTIMATION OF SURFACE DRAG
!     *RLPEVAP*   REAL     FRACTION OF POSSIBLE RAINFALL EVAPORATION
!     *RLPP00*    REAL     PRESSURE ABOVE WHICH RADIATION IS NOT APPLIED
!     *LTLEVOL*   LOGICAL  SWITCH FOR TL EVOLUTION OF PERTURBATION RUN
!     *LPHYLIN*   LOGICAL  TRUE WHEN LINEARIZED PHYSICS IS ACTIVATED 
!     *LENOPERT   LOGICAL  TRUE WHEN NO PERTURBATION IS REQUIRED
!                          FOR SURFACE ARRAYS
!     *LEPPCFLS   LOGICAL  TRUE WHEN POST-PROCESSING OF SURFACE FIELDS 
!                          REQUIRED
!     *LRAISANEN  LOGICAL  TRUE WHEN RAISANEN OVERLAP SCHEME IS
!                          ACTIVATED
!     ------------------------------------------------------------------

CONTAINS

  SUBROUTINE YREPHLI_LOAD_PARAMETERS()
    ALLOCATE(YREPHLI)
    CALL LOAD_SCALAR('YREPHLI_LTLEVOL', YREPHLI%LTLEVOL)
    CALL LOAD_SCALAR('YREPHLI_LPHYLIN', YREPHLI%LPHYLIN)
    CALL LOAD_SCALAR('YREPHLI_LENOPERT', YREPHLI%LENOPERT)
    CALL LOAD_SCALAR('YREPHLI_LEPPCFLS', YREPHLI%LEPPCFLS)
    CALL LOAD_SCALAR('YREPHLI_LRAISANEN', YREPHLI%LRAISANEN)
    CALL LOAD_SCALAR('YREPHLI_RLPTRC', YREPHLI%RLPTRC)
    CALL LOAD_SCALAR('YREPHLI_RLPAL1', YREPHLI%RLPAL1)
    CALL LOAD_SCALAR('YREPHLI_RLPAL2', YREPHLI%RLPAL2)
    CALL LOAD_SCALAR('YREPHLI_RLPBB', YREPHLI%RLPBB)
    CALL LOAD_SCALAR('YREPHLI_RLPCC', YREPHLI%RLPCC)
    CALL LOAD_SCALAR('YREPHLI_RLPDD', YREPHLI%RLPDD)
    CALL LOAD_SCALAR('YREPHLI_RLPMIXL', YREPHLI%RLPMIXL)
    CALL LOAD_SCALAR('YREPHLI_RLPBETA', YREPHLI%RLPBETA)
    CALL LOAD_SCALAR('YREPHLI_RLPDRAG', YREPHLI%RLPDRAG)
    CALL LOAD_SCALAR('YREPHLI_RLPEVAP', YREPHLI%RLPEVAP)
    CALL LOAD_SCALAR('YREPHLI_RLPP00', YREPHLI%RLPP00)
  END SUBROUTINE YREPHLI_LOAD_PARAMETERS

END MODULE YOEPHLI
