! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE YOETHF_CUF

USE PARKIND1, ONLY : JPIM, JPRB

USE YOETHF, ONLY: R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, R5ALVCP, &
 & R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE,  &
 & RTICECU, RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2, &
 & RVTMP2,RHOH2O,RTBER,RTBERCU

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!*     *YOETHF* DERIVED CONSTANTS SPECIFIC TO ECMWF THERMODYNAMICS
!     ------------------------------------------------------------------

REAL(KIND=JPRB) , CONSTANT :: R2ES_D
REAL(KIND=JPRB) , CONSTANT :: R3LES_D
REAL(KIND=JPRB) , CONSTANT :: R3IES_D
REAL(KIND=JPRB) , CONSTANT :: R4LES_D
REAL(KIND=JPRB) , CONSTANT :: R4IES_D
REAL(KIND=JPRB) , CONSTANT :: R5LES_D
REAL(KIND=JPRB) , CONSTANT :: R5IES_D
REAL(KIND=JPRB) , CONSTANT :: RVTMP2_D
REAL(KIND=JPRB) , CONSTANT :: RHOH2O_D
REAL(KIND=JPRB) , CONSTANT :: R5ALVCP_D
REAL(KIND=JPRB) , CONSTANT :: R5ALSCP_D
REAL(KIND=JPRB) , CONSTANT :: RALVDCP_D
REAL(KIND=JPRB) , CONSTANT :: RALSDCP_D
REAL(KIND=JPRB) , CONSTANT :: RALFDCP_D
REAL(KIND=JPRB) , CONSTANT :: RTWAT_D
REAL(KIND=JPRB) , CONSTANT :: RTBER_D
REAL(KIND=JPRB) , CONSTANT :: RTBERCU_D
REAL(KIND=JPRB) , CONSTANT :: RTICE_D
REAL(KIND=JPRB) , CONSTANT :: RTICECU_D
REAL(KIND=JPRB) , CONSTANT :: RTWAT_RTICE_R_D
REAL(KIND=JPRB) , CONSTANT :: RTWAT_RTICECU_R_D
REAL(KIND=JPRB) , CONSTANT :: RKOOP1_D
REAL(KIND=JPRB) , CONSTANT :: RKOOP2_D

!     J.-J. MORCRETTE                   91/07/14  ADAPTED TO I.F.S.

!      NAME     TYPE      PURPOSE
!      ----     ----      -------

!     *R__ES*   REAL      *CONSTANTS USED FOR COMPUTATION OF SATURATION
!                         MIXING RATIO OVER LIQUID WATER(*R_LES*) OR
!                         ICE(*R_IES*).
!     *RVTMP2*  REAL      *RVTMP2=RCPV/RCPD-1.
!     *RHOH2O*  REAL      *DENSITY OF LIQUID WATER.   (RATM/100.)
!     *R5ALVCP* REAL      *R5LES*RLVTT/RCPD
!     *R5ALSCP* REAL      *R5IES*RLSTT/RCPD
!     *RALVDCP* REAL      *RLVTT/RCPD
!     *RALSDCP* REAL      *RLSTT/RCPD
!     *RALFDCP* REAL      *RLMLT/RCPD
!     *RTWAT*   REAL      *RTWAT=RTT
!     *RTBER*   REAL      *RTBER=RTT-0.05
!     *RTBERCU  REAL      *RTBERCU=RTT-5.0
!     *RTICE*   REAL      *RTICE=RTT-0.1
!     *RTICECU* REAL      *RTICECU=RTT-23.0
!     *RKOOP?   REAL      *CONSTANTS TO DESCRIBE KOOP FORM FOR NUCLEATION
!     *RTWAT_RTICE_R*   REAL      *RTWAT_RTICE_R=1./(RTWAT-RTICE)
!     *RTWAT_RTICECU_R* REAL      *RTWAT_RTICECU_R=1./(RTWAT-RTICECU)


!       ----------------------------------------------------------------

CONTAINS

ATTRIBUTES(HOST)  SUBROUTINE YOETHF_UPDATE_DEVICE()

  R2ES_D=R2ES; R3LES_D=R3LES; R3IES_D=R3IES; R4LES_D=R4LES; R4IES_D=R4IES; R5LES_D=R5LES; R5IES_D=R5IES;
  RVTMP2_D=RVTMP2; RHOH2O_D=RHOH2O; R5ALVCP_D=R5ALVCP; R5ALSCP_D=R5ALSCP; RALVDCP_D=RALVDCP; RALSDCP_D=RALSDCP;
  RALFDCP_D=RALFDCP; RTWAT_D=RTWAT; RTBER_D=RTBER; RTBERCU_D=RTBERCU; RTICE_D=RTICE; RTICECU_D=RTICECU;
  RTWAT_RTICE_R_D=RTWAT_RTICE_R; RTWAT_RTICECU_R_D=RTWAT_RTICECU_R; RKOOP1_D=RKOOP1; RKOOP2_D=RKOOP2
END SUBROUTINE YOETHF_UPDATE_DEVICE

END MODULE YOETHF_CUF
