#!/bin/sh
MULT=${1:-1}

CPUFILE=/proc/cpuinfo

# Logical number of cores
NUMLOG=1
if test -f $CPUFILE ; then
    NUMLOG=$(grep "processor" $CPUFILE | wc -l)
fi
#echo $NUMLOG

# Physical number of sockets
NUMPHY=$(grep "physical id" $CPUFILE | sort -u | wc -l)
#echo $NUMPHY

# N-way hyperthreading
HT=1
if [ $NUMLOG -gt 1 ] ; then
    HT=`expr $NUMLOG / $NUMPHY`
    NUMCORE=$(grep "core id" $CPUFILE | sort -u | wc -l)
#    echo $NUMCORE
    if [ $NUMCORE -gt 1 ] ; then
	HT=`expr $HT / $NUMCORE`
    fi
fi
#echo $HT

NUMPHYS=`expr $NUMLOG / $HT`

NUM=`expr $NUMPHYS \* $MULT`
echo $NUM

exit 0
