MODULE CLOUDSC_INIT_VEC_MOD
CONTAINS

SUBROUTINE CLOUDSC_INIT_VEC (TENDENCY_T, TENDENCY_Q, TENDENCY_A, KLON, KLEV, KIDIA, KFDIA)
    USE PARKIND1 , ONLY : JPRB, JPIM

    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_T(KLON, KLEV)
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_Q(KLON, KLEV)
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_A(KLON, KLEV)
    INTEGER(KIND=JPIM),INTENT(IN)    :: KLON, KLEV
    INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
    INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
    INTEGER(KIND=JPIM) :: JK, JL

    DO JK=1,KLEV
      DO JL=KIDIA,KFDIA
        TENDENCY_T(JL,JK)=0.0_JPRB
        TENDENCY_Q(JL,JK)=0.0_JPRB
        TENDENCY_A(JL,JK)=0.0_JPRB
      ENDDO
    ENDDO

END SUBROUTINE CLOUDSC_INIT_VEC
END MODULE CLOUDSC_INIT_VEC_MOD
