MODULE CLOUDSC_INIT_SEQ_MOD
CONTAINS

ELEMENTAL SUBROUTINE CLOUDSC_INIT_SEQ (TENDENCY_T, TENDENCY_Q, TENDENCY_A)
    USE PARKIND1 , ONLY : JPRB
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_T
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_Q
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: TENDENCY_A
    
    TENDENCY_T=0.0_JPRB
    TENDENCY_Q=0.0_JPRB
    TENDENCY_A=0.0_JPRB
END SUBROUTINE CLOUDSC_INIT_SEQ
END MODULE CLOUDSC_INIT_SEQ_MOD
