#!/bin/sh
host=$(hostname)
echo "${host}: $(date)" 
echo "${host}: $(uname -a)" 
CPUFILE=/proc/cpuinfo
test -f $CPUFILE || exit 0
NUMPHY=$(grep "physical id" $CPUFILE | sort -u | wc -l)
NUMLOG=$(grep "processor" $CPUFILE | wc -l)
if [ $NUMPHY -eq 1 ] ; then
    echo -n "${host}: This system has one CPU-socket"
else
    echo -n "${host}: This system has $NUMPHY CPU-sockets"
fi
HT=1
if [ $NUMLOG -gt 1 ] ; then
    HT=`expr $NUMLOG / $NUMPHY`
    echo " and $NUMLOG logical H/W threads."
    NUMCORE=$(grep "core id" $CPUFILE | sort -u | wc -l)
    if [ $NUMCORE -gt 1 ] ; then
        echo "${host}: For every CPU-socket there are $NUMCORE cores."
	HT=`expr $HT / $NUMCORE`
    fi
else
    echo " and one logical CPU."
fi
echo -n "${host}: The CPU is a"$(grep "model name" $CPUFILE | sort -u | cut -d : -f 2-)
#echo -n " ("$(grep "cpu MHz" $CPUFILE  | sort -u | cut -d : -f 2- | sed 's/\n/ /' |awk '{for (i=1;i<=NF;++i) printf("%g ",$i/1000.0)}')"GHz)"
echo " with"$(grep "cache size" $CPUFILE | sort -u | cut -d : -f 2-)" cache"

if [ $HT -gt 1 ] ; then
    ht=enabled
    grep -o '^flags\b.*: .*\bht\b' >/dev/null 2>&1 $CPUFILE || ht=disabled
    echo "${host}: Hyper-threading is $HT-way and is $ht"
else
    echo "${host}: Hyper-threading is disabled"
fi

MEMFILE=/proc/meminfo
test -f $MEMFILE || exit 0
TOTMEM=$(grep MemTotal $MEMFILE | awk '{$1=""; print $0;}' | sed 's/^[\t ]*//')
echo "${host}: Memory size is $TOTMEM"

