! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE CLOUDSC_DRIVER_FIELD_MOD
  USE PARKIND1, ONLY: JPIM, JPIB, JPRB, JPRD
  USE YOMPHYDER, ONLY: STATE_TYPE
  USE YOECLDP, ONLY : NCLV
  USE CLOUDSC_MPI_MOD, ONLY: NUMPROC, IRANK
  USE TIMER_MOD, ONLY : PERFORMANCE_TIMER, GET_THREAD_NUM
  USE CLOUDSC_FIELD_STATE_MOD, ONLY: CLOUDSC_AUX_TYPE, CLOUDSC_FLUX_TYPE, CLOUDSC_STATE_TYPE

  IMPLICIT NONE

CONTAINS

  SUBROUTINE CLOUDSC_DRIVER_FIELD( &
     & NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG, KFLDX, PTSPHY, PAUX, FLUX, &
     & TENDENCY_TMP, TENDENCY_LOC, YDOMCST, YDOETHF, YDECLDP)
    
    USE YOECLDP  , ONLY : TECLDP
    USE YOMCST   , ONLY : TOMCST
    USE YOETHF   , ONLY : TOETHF

    INTEGER(KIND=JPIM)        ,INTENT(IN) :: NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG
    INTEGER(KIND=JPIM)        ,INTENT(IN) :: KFLDX 
    REAL(KIND=JPRB)           ,INTENT(IN) :: PTSPHY       ! PHYSICS TIMESTEP
    TYPE(CLOUDSC_AUX_TYPE)    ,INTENT(IN) :: PAUX
    TYPE(CLOUDSC_FLUX_TYPE)   ,INTENT(IN) :: FLUX
    TYPE(CLOUDSC_STATE_TYPE)  ,INTENT(IN) :: TENDENCY_TMP
    TYPE(CLOUDSC_STATE_TYPE)  ,INTENT(INOUT) :: TENDENCY_LOC
    TYPE(TOMCST)              , INTENT(INOUT) :: YDOMCST
    TYPE(TOETHF)              , INTENT(INOUT) :: YDOETHF
    TYPE(TECLDP)              , INTENT(INOUT) :: YDECLDP

    INTEGER(KIND=JPIM) :: JKGLO,IBL,ICEND, NGPBLKS
    
    TYPE(PERFORMANCE_TIMER) :: TIMER
    INTEGER(KIND=JPIM) :: TID ! thread id from 0 .. NUMOMP - 1

    NGPBLKS = (NGPTOT / NPROMA) + MIN(MOD(NGPTOT,NPROMA), 1)
1003 format(5x,'NUMPROC=',i0,', NUMOMP=',i0,', NGPTOTG=',i0,', NPROMA=',i0,', NGPBLKS=',i0)
    if (irank == 0) then
      write(0,1003) NUMPROC,NUMOMP,NGPTOTG,NPROMA,NGPBLKS
    end if

#ifdef FIELD_API_IO 
    CALL TEST_FIELD_HDF5(NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG, KFLDX, PTSPHY, PAUX, &
                       & TENDENCY_TMP, TENDENCY_LOC) 
#endif

    ! Global timer for the parallel region
    CALL TIMER%START(NUMOMP)

    !$omp parallel default(shared) private(JKGLO,IBL,ICEND,TID) &
    !$omp& num_threads(NUMOMP) firstprivate(PAUX, FLUX, TENDENCY_TMP, TENDENCY_LOC)

    ! Local timer for each thread
    TID = GET_THREAD_NUM()
    CALL TIMER%THREAD_START(TID)

    !$omp do schedule(runtime)
    DO JKGLO=1,NGPTOT,NPROMA
        IBL=(JKGLO-1)/NPROMA+1
        ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)

        CALL PAUX%UPDATE_VIEW(IBL)
        CALL FLUX%UPDATE_VIEW(IBL)
        CALL TENDENCY_LOC%UPDATE_VIEW(IBL)
        CALL TENDENCY_TMP%UPDATE_VIEW(IBL)

        CALL CLOUDSC(    1,    ICEND,    NPROMA,  NLEV, & ! These could also be accessed through FIELD_STATE
              & PTSPHY,&
              & PAUX%PT, PAUX%PQ, &
              & TENDENCY_TMP%T, TENDENCY_TMP%Q, TENDENCY_TMP%A, TENDENCY_TMP%CLD, &
              & TENDENCY_LOC%T, TENDENCY_LOC%Q, TENDENCY_LOC%A, TENDENCY_LOC%CLD, &
              & PAUX%PVFA, PAUX%PVFL, PAUX%PVFI, PAUX%PDYNA, PAUX%PDYNL, PAUX%PDYNI, &
              & PAUX%PHRSW,    PAUX%PHRLW,&
              & PAUX%PVERVEL,  PAUX%PAP,      PAUX%PAPH,&
              & PAUX%PLSM,     PAUX%LDCUM,    PAUX%KTYPE, &
              & PAUX%PLU,      PAUX%PLUDE,    PAUX%PSNDE,    PAUX%PMFU,     PAUX%PMFD,&
              !---prognostic fields
              & PAUX%PA,&
              & PAUX%PCLV,  &
              & PAUX%PSUPSAT,&
!             -- arrays for aerosol-cloud interactions
!             !! & PQAER,    KAER, &
              & PAUX%PLCRIT_AER,PAUX%PICRIT_AER,&
              & PAUX%PRE_ICE,&
              & PAUX%PCCN,     PAUX%PNICE,&
              !---diagnostic output
              & PAUX%PCOVPTOT, PAUX%PRAINFRAC_TOPRFZ,&
              !---resulting fluxes
              & FLUX%PFSQLF,   FLUX%PFSQIF ,  FLUX%PFCQNNG,  FLUX%PFCQLNG,&
              & FLUX%PFSQRF,   FLUX%PFSQSF ,  FLUX%PFCQRNG,  FLUX%PFCQSNG,&
              & FLUX%PFSQLTUR, FLUX%PFSQITUR , &
              & FLUX%PFPLSL,   FLUX%PFPLSN,   FLUX%PFHPSL,   FLUX%PFHPSN, KFLDX, &
              & YDOMCST, YDOETHF, YDECLDP)

        ! Log number of columns processed by this thread
        CALL TIMER%THREAD_LOG(TID, IGPC=ICEND)
      ENDDO

      !-- The "nowait" is here to get correct local timings (tloc) per thread
      !   i.e. we should not wait for slowest thread to finish before measuring tloc
      !$omp end do nowait

      CALL TIMER%THREAD_END(TID)

      !$omp end parallel

      CALL TIMER%END()

      CALL TIMER%PRINT_PERFORMANCE(NPROMA, NGPBLKS, NGPTOT)
    
  END SUBROUTINE CLOUDSC_DRIVER_FIELD
#ifdef FIELD_API_IO 
  SUBROUTINE TEST_FIELD_HDF5( &
     & NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG, KFLDX, PTSPHY, PAUX, &
     & TENDENCY_TMP, TENDENCY_LOC)
    ! Driver routine that invokes the optimized CLAW-based CLOUDSC GPU kernel
    
    USE FIELD_HDF5_MODULE, ONLY: WRITE_HDF5_PERRANK_DATA, READ_HDF5_PERRANK_DATA
    INTEGER(KIND=JPIM)        ,INTENT(IN) :: NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG
    INTEGER(KIND=JPIM)        ,INTENT(IN) :: KFLDX 
    REAL(KIND=JPRB)           ,INTENT(IN) :: PTSPHY       ! PHYSICS TIMESTEP
    TYPE(CLOUDSC_AUX_TYPE)    ,INTENT(IN) :: PAUX
    TYPE(CLOUDSC_STATE_TYPE)  ,INTENT(IN) :: TENDENCY_TMP
    TYPE(CLOUDSC_STATE_TYPE)  ,INTENT(IN) :: TENDENCY_LOC

    REAL(KIND=JPRB), POINTER    :: PAUX_PT(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PQ(:,:,:)

    REAL(KIND=JPRB), POINTER    :: TENDENCY_TMP_T(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_TMP_Q(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_TMP_A(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_TMP_CLD(:,:,:,:)

    REAL(KIND=JPRB), POINTER    :: TENDENCY_LOC_T(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_LOC_Q(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_LOC_A(:,:,:)
    REAL(KIND=JPRB), POINTER    :: TENDENCY_LOC_CLD(:,:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PVFA(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PVFL(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PVFI(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PDYNA(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PDYNL(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PDYNI(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PHRSW(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PHRLW(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PVERVEL(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PAP(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PAPH(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PLSM(:,:)
    LOGICAL,            POINTER :: PAUX_LDCUM(:,:)
    INTEGER(KIND=JPIM), POINTER :: PAUX_KTYPE(:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PLU(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PLUDE(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PSNDE(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PMFU(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PMFD(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PA(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PCLV(:,:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PSUPSAT(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PLCRIT_AER(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PICRIT_AER(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PRE_ICE_AER(:,:,:)

    REAL(KIND=JPRB), POINTER    :: PAUX_PCCN(:,:,:)
    REAL(KIND=JPRB), POINTER    :: PAUX_PNICE(:,:,:)

    CALL PAUX%F_PT%GET_HOST_DATA_RDONLY(PAUX_PT)
    CALL PAUX%F_PQ%GET_HOST_DATA_RDONLY(PAUX_PQ)

    CALL TENDENCY_TMP%F_T%GET_DEVICE_DATA_RDONLY(TENDENCY_TMP_T)
    CALL TENDENCY_TMP%F_Q%GET_DEVICE_DATA_RDONLY(TENDENCY_TMP_Q)
    CALL TENDENCY_TMP%F_A%GET_DEVICE_DATA_RDONLY(TENDENCY_TMP_A)
    CALL TENDENCY_TMP%F_CLD%GET_DEVICE_DATA_RDONLY(TENDENCY_TMP_CLD)

    CALL TENDENCY_LOC%F_T%GET_DEVICE_DATA_RDONLY(TENDENCY_LOC_T)
    CALL TENDENCY_LOC%F_Q%GET_DEVICE_DATA_RDONLY(TENDENCY_LOC_Q)
    CALL TENDENCY_LOC%F_A%GET_DEVICE_DATA_RDONLY(TENDENCY_LOC_A)
    CALL TENDENCY_LOC%F_CLD%GET_DEVICE_DATA_RDONLY(TENDENCY_LOC_CLD)

    CALL PAUX%F_PVFA%GET_HOST_DATA_RDONLY(PAUX_PVFA)
    CALL PAUX%F_PVFL%GET_HOST_DATA_RDONLY(PAUX_PVFL)
    CALL PAUX%F_PVFI%GET_HOST_DATA_RDONLY(PAUX_PVFI)
    CALL PAUX%F_PDYNA%GET_HOST_DATA_RDONLY(PAUX_PDYNA)
    CALL PAUX%F_PDYNL%GET_HOST_DATA_RDONLY(PAUX_PDYNL)
    CALL PAUX%F_PDYNI%GET_HOST_DATA_RDONLY(PAUX_PDYNI)

    CALL PAUX%F_PHRSW%GET_HOST_DATA_RDONLY(PAUX_PHRSW)
    CALL PAUX%F_PHRLW%GET_HOST_DATA_RDONLY(PAUX_PHRLW)

    CALL PAUX%F_PVERVEL%GET_HOST_DATA_RDONLY(PAUX_PVERVEL)
    CALL PAUX%F_PAP%GET_HOST_DATA_RDONLY(PAUX_PAP)
    CALL PAUX%F_PAPH%GET_HOST_DATA_RDONLY(PAUX_PAPH)

    CALL PAUX%F_PLSM%GET_HOST_DATA_RDONLY(PAUX_PLSM)
    CALL PAUX%F_LDCUM%GET_HOST_DATA_RDONLY(PAUX_LDCUM)
    CALL PAUX%F_KTYPE%GET_HOST_DATA_RDONLY(PAUX_KTYPE)

    CALL PAUX%F_PLU%GET_HOST_DATA_RDONLY(PAUX_PLU)
    CALL PAUX%F_PLUDE%GET_HOST_DATA_RDONLY(PAUX_PLUDE)
    CALL PAUX%F_PSNDE%GET_HOST_DATA_RDONLY(PAUX_PSNDE)
    CALL PAUX%F_PMFU%GET_HOST_DATA_RDONLY(PAUX_PMFU)
    CALL PAUX%F_PMFD%GET_HOST_DATA_RDONLY(PAUX_PMFD)

    CALL PAUX%F_PA%GET_HOST_DATA_RDONLY(PAUX_PA)
    CALL PAUX%F_PCLV%GET_HOST_DATA_RDONLY(PAUX_PCLV)
    CALL PAUX%F_PSUPSAT%GET_HOST_DATA_RDONLY(PAUX_PSUPSAT)

    CALL PAUX%F_PLCRIT_AER%GET_HOST_DATA_RDONLY(PAUX_PLCRIT_AER)
    CALL PAUX%F_PICRIT_AER%GET_HOST_DATA_RDONLY(PAUX_PICRIT_AER)

    CALL PAUX%F_PRE_ICE%GET_HOST_DATA_RDONLY(PAUX_PRE_ICE_AER)

    CALL PAUX%F_PCCN%GET_HOST_DATA_RDONLY(PAUX_PCCN)
    CALL PAUX%F_PNICE%GET_HOST_DATA_RDONLY(PAUX_PNICE)

    ! 4D fields

    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PT, PAUX_PVERVEL, "cloudsc_data", "PT",           HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PQ, PAUX_PVERVEL, "cloudsc_data", "PQ",           HDFEXISTS=.TRUE.)

    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_TMP%F_T,   TENDENCY_TMP_T,   "cloudsc_data", "TEND_TMP_T",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_TMP%F_Q,   TENDENCY_TMP_Q,   "cloudsc_data", "TEND_TMP_Q",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_TMP%F_A,   TENDENCY_TMP_A,   "cloudsc_data", "TEND_TMP_A",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_TMP%F_CLD, TENDENCY_TMP_CLD, "cloudsc_data", "TEND_TMP_CLD", HDFEXISTS=.TRUE.)

    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_LOC%F_T,   TENDENCY_LOC_T,   "cloudsc_data", "TEND_LOC_T",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_LOC%F_Q,   TENDENCY_LOC_Q,   "cloudsc_data", "TEND_LOC_Q",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_LOC%F_A,   TENDENCY_LOC_A,   "cloudsc_data", "TEND_LOC_A",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(TENDENCY_LOC%F_CLD, TENDENCY_LOC_CLD, "cloudsc_data", "TEND_LOC_CLD", HDFEXISTS=.TRUE.)

    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PVFA,     PAUX_PVFA, "cloudsc_data", "PVFA",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PVFL,     PAUX_PVFL, "cloudsc_data", "PVFL",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PVFI,     PAUX_PVFI, "cloudsc_data", "PVFI",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PDYNA,   PAUX_PDYNA, "cloudsc_data", "PDYNA",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PDYNL,   PAUX_PDYNL, "cloudsc_data", "PDYNL",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PDYNI,   PAUX_PDYNI, "cloudsc_data", "PDYNI",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PHRSW,   PAUX_PHRSW, "cloudsc_data", "PHRSW",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PHRLW,   PAUX_PHRLW, "cloudsc_data", "PHRLW",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PVERVEL, PAUX_PVERVEL, "cloudsc_data", "PVERVEL",      HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PAP,         PAUX_PAP, "cloudsc_data", "PAP",          HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PAPH,       PAUX_PAPH, "cloudsc_data", "PAPH",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PLSM,       PAUX_PLSM, "cloudsc_data", "PLSM" ,        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_LDCUM,     PAUX_LDCUM, "cloudsc_data", "LDCUM",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_KTYPE,     PAUX_KTYPE, "cloudsc_data", "KTYPE",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PLU,         PAUX_PLU, "cloudsc_data", "PLU",          HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PLUDE,     PAUX_PLUDE, "cloudsc_data", "PLUDE",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PSNDE,     PAUX_PSNDE, "cloudsc_data", "PSNDE",        HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PMFU,       PAUX_PMFU, "cloudsc_data", "PMFU",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PMFD,       PAUX_PMFD, "cloudsc_data", "PMFD",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PA,           PAUX_PA, "cloudsc_data", "PA",           HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PCLV,       PAUX_PCLV, "cloudsc_data", "PCLV",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PSUPSAT,  PAUX_PSUPSAT, "cloudsc_data", "PSUPSAT",      HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PLCRIT_AER, PAUX_PLCRIT_AER, "cloudsc_data", "PLCRIT_AER",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PICRIT_AER, PAUX_PICRIT_AER, "cloudsc_data", "PICRIT_AER",   HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PRE_ICE,   PAUX_PRE_ICE_AER, "cloudsc_data", "PRE_ICE_AER",  HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PCCN ,            PAUX_PCCN, "cloudsc_data", "PCCN",         HDFEXISTS=.TRUE.)
    CALL WRITE_HDF5_PERRANK_DATA(PAUX%F_PNICE,           PAUX_PNICE, "cloudsc_data", "PNICE",        HDFEXISTS=.TRUE.)


    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PT, PAUX_PVERVEL, "cloudsc_data", "PT", HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PQ, PAUX_PVERVEL, "cloudsc_data", "PQ", HDFEXISTS=.TRUE.)

    CALL READ_HDF5_PERRANK_DATA(TENDENCY_TMP%F_T,   TENDENCY_TMP_T,   "cloudsc_data", "TEND_TMP_T",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_TMP%F_Q,   TENDENCY_TMP_Q,   "cloudsc_data", "TEND_TMP_Q",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_TMP%F_A,   TENDENCY_TMP_A,   "cloudsc_data", "TEND_TMP_A",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_TMP%F_CLD, TENDENCY_TMP_CLD, "cloudsc_data", "TEND_TMP_CLD", HDFEXISTS=.TRUE.)

    CALL READ_HDF5_PERRANK_DATA(TENDENCY_LOC%F_T,   TENDENCY_LOC_T,   "cloudsc_data", "TEND_LOC_T",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_LOC%F_Q,   TENDENCY_LOC_Q,   "cloudsc_data", "TEND_LOC_Q",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_LOC%F_A,   TENDENCY_LOC_A,   "cloudsc_data", "TEND_LOC_A",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(TENDENCY_LOC%F_CLD, TENDENCY_LOC_CLD, "cloudsc_data", "TEND_LOC_CLD", HDFEXISTS=.TRUE.)

    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PVFA,     PAUX_PVFA, "cloudsc_data", "PVFA",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PVFL,     PAUX_PVFL, "cloudsc_data", "PVFL",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PVFI,     PAUX_PVFI, "cloudsc_data", "PVFI",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PDYNA,   PAUX_PDYNA, "cloudsc_data", "PDYNA",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PDYNL,   PAUX_PDYNL, "cloudsc_data", "PDYNL",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PDYNI,   PAUX_PDYNI, "cloudsc_data", "PDYNI",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PHRSW,   PAUX_PHRSW, "cloudsc_data", "PHRSW",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PHRLW,   PAUX_PHRLW, "cloudsc_data", "PHRLW",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PVERVEL, PAUX_PVERVEL, "cloudsc_data", "PVERVEL",      HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PAP,         PAUX_PAP, "cloudsc_data", "PAP",          HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PAPH,       PAUX_PAPH, "cloudsc_data", "PAPH",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PLSM,       PAUX_PLSM, "cloudsc_data", "PLSM" ,        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_LDCUM,     PAUX_LDCUM, "cloudsc_data", "LDCUM",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_KTYPE,     PAUX_KTYPE, "cloudsc_data", "KTYPE",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PLU,         PAUX_PLU, "cloudsc_data", "PLU",          HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PLUDE,     PAUX_PLUDE, "cloudsc_data", "PLUDE",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PSNDE,     PAUX_PSNDE, "cloudsc_data", "PSNDE",        HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PMFU,       PAUX_PMFU, "cloudsc_data", "PMFU",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PMFD,       PAUX_PMFD, "cloudsc_data", "PMFD",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PA,           PAUX_PA, "cloudsc_data", "PA",           HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PCLV,       PAUX_PCLV, "cloudsc_data", "PCLV",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PSUPSAT,  PAUX_PSUPSAT, "cloudsc_data", "PSUPSAT",      HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PLCRIT_AER, PAUX_PLCRIT_AER, "cloudsc_data", "PLCRIT_AER",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PICRIT_AER, PAUX_PICRIT_AER, "cloudsc_data", "PICRIT_AER",   HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PRE_ICE,   PAUX_PRE_ICE_AER, "cloudsc_data", "PRE_ICE_AER",  HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PCCN ,            PAUX_PCCN, "cloudsc_data", "PCCN",         HDFEXISTS=.TRUE.)
    CALL READ_HDF5_PERRANK_DATA(PAUX%F_PNICE,           PAUX_PNICE, "cloudsc_data", "PNICE",        HDFEXISTS=.TRUE.)

  END SUBROUTINE TEST_FIELD_HDF5
#endif


END MODULE CLOUDSC_DRIVER_FIELD_MOD

