MODULE CLOUDSC_INIT_VEC_MOD
CONTAINS

SUBROUTINE CLOUDSC_INIT_VEC (PCOVPTOT, KLON, KLEV, KIDIA, KFDIA)
    USE PARKIND1 , ONLY : JPRB, JPIM

    REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCOVPTOT(KLON, KLEV)
    INTEGER(KIND=JPIM),INTENT(IN)    :: KLON, KLEV
    INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
    INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
    INTEGER(KIND=JPIM) :: JK, JL

    DO JK=1,KLEV
      DO JL=KIDIA,KFDIA
        PCOVPTOT(JL,JK)=0.0_JPRB
      ENDDO
    ENDDO

END SUBROUTINE CLOUDSC_INIT_VEC
END MODULE CLOUDSC_INIT_VEC_MOD
