MODULE CLOUDSC_INIT_SEQ_MOD
CONTAINS

ELEMENTAL SUBROUTINE CLOUDSC_INIT_SEQ (PCOVPTOT)
    USE PARKIND1 , ONLY : JPRB
    REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCOVPTOT
    
    !$loki routine seq

    PCOVPTOT=0.0_JPRB
END SUBROUTINE CLOUDSC_INIT_SEQ
END MODULE CLOUDSC_INIT_SEQ_MOD
