! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
MODULE CLOUDSC_DRIVER_GPU_SCC_CUF_K_CACHING_MOD
  USE cudafor
  USE PARKIND1, ONLY: JPIM, JPIB, JPRB, JPRD
  USE YOMPHYDER, ONLY: STATE_TYPE
  USE YOECLDP, ONLY: NCLV, YRECLDP, TECLDP
  USE CLOUDSC_MPI_MOD, ONLY: NUMPROC, IRANK
  USE TIMER_MOD, ONLY: PERFORMANCE_TIMER, GET_THREAD_NUM
  
  USE YOMCST_CUF, ONLY: YOMCST_UPDATE_DEVICE
  USE YOETHF_CUF, ONLY: YOETHF_UPDATE_DEVICE
  
  USE CLOUDSC_GPU_SCC_CUF_K_CACHING_MOD, ONLY: CLOUDSC_SCC_CUF_K_CACHING

  IMPLICIT NONE
  
  CONTAINS
  
  SUBROUTINE CLOUDSC_DRIVER_GPU_SCC_CUF_K_CACHING (NUMOMP, NPROMA, NLEV, NGPTOT, NGPTOTG, NGPBLKS, KFLDX, PTSPHY, PT, PQ, TENDENCY_CML, TENDENCY_TMP,  &
  & TENDENCY_LOC, BUFFER_CML, BUFFER_TMP, BUFFER_LOC, PVFA, PVFL, PVFI, PDYNA, PDYNL, PDYNI, PHRSW, PHRLW, PVERVEL, PAP, PAPH,  &
  & PLSM, LDCUM, KTYPE, PLU, PLUDE, PSNDE, PMFU, PMFD, PA, PCLV, PSUPSAT, PLCRIT_AER, PICRIT_AER, PRE_ICE, PCCN, PNICE,  &
  & PCOVPTOT, PRAINFRAC_TOPRFZ, PFSQLF, PFSQIF, PFCQNNG, PFCQLNG, PFSQRF, PFSQSF, PFCQRNG, PFCQSNG, PFSQLTUR, PFSQITUR, PFPLSL,  &
  & PFPLSN, PFHPSL, PFHPSN)
    ! Driver routine that performans the parallel NPROMA-blocking and
    ! invokes the CLOUDSC kernel
    
    
    INTEGER(KIND=JPIM), INTENT(IN) :: NUMOMP, NPROMA, NLEV, NGPTOT, NGPBLKS, NGPTOTG
    INTEGER(KIND=JPIM), INTENT(IN) :: KFLDX
    REAL(KIND=JPRB), INTENT(IN) :: PTSPHY    ! Physics timestep
    REAL(KIND=JPRB), INTENT(IN) :: PT(NPROMA, NLEV, NGPBLKS)    ! T at start of callpar
    REAL(KIND=JPRB), INTENT(IN) :: PQ(NPROMA, NLEV, NGPBLKS)    ! Q at start of callpar
    TYPE(state_type), INTENT(IN) :: TENDENCY_CML(NGPBLKS)    ! cumulative tendency used for final output
    TYPE(state_type), INTENT(IN) :: TENDENCY_TMP(NGPBLKS)    ! cumulative tendency used as input
    TYPE(state_type), INTENT(OUT) :: TENDENCY_LOC(NGPBLKS)    ! local tendency from cloud scheme
    REAL(KIND=JPRB), INTENT(INOUT) :: BUFFER_CML(NPROMA, NLEV, 3 + NCLV, NGPBLKS)    ! Storage buffer for TENDENCY_CML
    REAL(KIND=JPRB), INTENT(INOUT) :: BUFFER_TMP(NPROMA, NLEV, 3 + NCLV, NGPBLKS)    ! Storage buffer for TENDENCY_TMP
    REAL(KIND=JPRB), INTENT(INOUT) :: BUFFER_LOC(NPROMA, NLEV, 3 + NCLV, NGPBLKS)    ! Storage buffer for TENDENCY_LOC
    REAL(KIND=JPRB), INTENT(IN) :: PVFA(NPROMA, NLEV, NGPBLKS)    ! CC from VDF scheme
    REAL(KIND=JPRB), INTENT(IN) :: PVFL(NPROMA, NLEV, NGPBLKS)    ! Liq from VDF scheme
    REAL(KIND=JPRB), INTENT(IN) :: PVFI(NPROMA, NLEV, NGPBLKS)    ! Ice from VDF scheme
    REAL(KIND=JPRB), INTENT(IN) :: PDYNA(NPROMA, NLEV, NGPBLKS)    ! CC from Dynamics
    REAL(KIND=JPRB), INTENT(IN) :: PDYNL(NPROMA, NLEV, NGPBLKS)    ! Liq from Dynamics
    REAL(KIND=JPRB), INTENT(IN) :: PDYNI(NPROMA, NLEV, NGPBLKS)    ! Liq from Dynamics
    REAL(KIND=JPRB), INTENT(IN) :: PHRSW(NPROMA, NLEV, NGPBLKS)    ! Short-wave heating rate
    REAL(KIND=JPRB), INTENT(IN) :: PHRLW(NPROMA, NLEV, NGPBLKS)    ! Long-wave heating rate
    REAL(KIND=JPRB), INTENT(IN) :: PVERVEL(NPROMA, NLEV, NGPBLKS)    !Vertical velocity
    REAL(KIND=JPRB), INTENT(IN) :: PAP(NPROMA, NLEV, NGPBLKS)    ! Pressure on full levels
    REAL(KIND=JPRB), INTENT(IN) :: PAPH(NPROMA, NLEV + 1, NGPBLKS)    ! Pressure on half levels
    REAL(KIND=JPRB), INTENT(IN) :: PLSM(NPROMA, NGPBLKS)    ! Land fraction (0-1)
    LOGICAL, INTENT(IN) :: LDCUM(NPROMA, NGPBLKS)    ! Convection active
    INTEGER(KIND=JPIM), INTENT(IN) :: KTYPE(NPROMA, NGPBLKS)    ! Convection type 0,1,2
    REAL(KIND=JPRB), INTENT(IN) :: PLU(NPROMA, NLEV, NGPBLKS)    ! Conv. condensate
    REAL(KIND=JPRB), INTENT(INOUT) :: PLUDE(NPROMA, NLEV, NGPBLKS)    ! Conv. detrained water
    REAL(KIND=JPRB), INTENT(IN) :: PSNDE(NPROMA, NLEV, NGPBLKS)    ! Conv. detrained snow
    REAL(KIND=JPRB), INTENT(IN) :: PMFU(NPROMA, NLEV, NGPBLKS)    ! Conv. mass flux up
    REAL(KIND=JPRB), INTENT(IN) :: PMFD(NPROMA, NLEV, NGPBLKS)    ! Conv. mass flux down
    REAL(KIND=JPRB), INTENT(IN) :: PA(NPROMA, NLEV, NGPBLKS)    ! Original Cloud fraction (t)
    REAL(KIND=JPRB), INTENT(IN) :: PCLV(NPROMA, NLEV, NCLV, NGPBLKS)
    REAL(KIND=JPRB), INTENT(IN) :: PSUPSAT(NPROMA, NLEV, NGPBLKS)
    REAL(KIND=JPRB), INTENT(IN) :: PLCRIT_AER(NPROMA, NLEV, NGPBLKS)
    REAL(KIND=JPRB), INTENT(IN) :: PICRIT_AER(NPROMA, NLEV, NGPBLKS)
    REAL(KIND=JPRB), INTENT(IN) :: PRE_ICE(NPROMA, NLEV, NGPBLKS)
    REAL(KIND=JPRB), INTENT(IN) :: PCCN(NPROMA, NLEV, NGPBLKS)    ! liquid cloud condensation nuclei
    REAL(KIND=JPRB), INTENT(IN) :: PNICE(NPROMA, NLEV, NGPBLKS)    ! ice number concentration (cf. CCN)
    
    REAL(KIND=JPRB), INTENT(INOUT) :: PCOVPTOT(NPROMA, NLEV, NGPBLKS)    ! Precip fraction
    REAL(KIND=JPRB), INTENT(OUT) :: PRAINFRAC_TOPRFZ(NPROMA, NGPBLKS)
    ! Flux diagnostics for DDH budget
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQLF(NPROMA, NLEV + 1, NGPBLKS)    ! Flux of liquid
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQIF(NPROMA, NLEV + 1, NGPBLKS)    ! Flux of ice
    REAL(KIND=JPRB), INTENT(OUT) :: PFCQLNG(NPROMA, NLEV + 1, NGPBLKS)    ! -ve corr for liq
    REAL(KIND=JPRB), INTENT(OUT) :: PFCQNNG(NPROMA, NLEV + 1, NGPBLKS)    ! -ve corr for ice
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQRF(NPROMA, NLEV + 1, NGPBLKS)    ! Flux diagnostics
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQSF(NPROMA, NLEV + 1, NGPBLKS)    !    for DDH, generic
    REAL(KIND=JPRB), INTENT(OUT) :: PFCQRNG(NPROMA, NLEV + 1, NGPBLKS)    ! rain
    REAL(KIND=JPRB), INTENT(OUT) :: PFCQSNG(NPROMA, NLEV + 1, NGPBLKS)    ! snow
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQLTUR(NPROMA, NLEV + 1, NGPBLKS)    ! liquid flux due to VDF
    REAL(KIND=JPRB), INTENT(OUT) :: PFSQITUR(NPROMA, NLEV + 1, NGPBLKS)    ! ice flux due to VDF
    REAL(KIND=JPRB), INTENT(OUT) :: PFPLSL(NPROMA, NLEV + 1, NGPBLKS)    ! liq+rain sedim flux
    REAL(KIND=JPRB), INTENT(OUT) :: PFPLSN(NPROMA, NLEV + 1, NGPBLKS)    ! ice+snow sedim flux
    REAL(KIND=JPRB), INTENT(OUT) :: PFHPSL(NPROMA, NLEV + 1, NGPBLKS)    ! Enthalpy flux for liq
    REAL(KIND=JPRB), INTENT(OUT) :: PFHPSN(NPROMA, NLEV + 1, NGPBLKS)    ! Enthalp flux for ice
    
    INTEGER(KIND=JPIM) :: JKGLO, IBL, ICEND
    
    
    TYPE(PERFORMANCE_TIMER) :: TIMER
    INTEGER(KIND=JPIM) :: TID    ! thread id from 0 .. NUMOMP - 1
    TYPE(TECLDP), DEVICE :: YRECLDP_d
    INTEGER :: istat
    
    ! Device arrays
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PT_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PQ_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: BUFFER_TMP_d(:, :, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: BUFFER_LOC_d(:, :, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PVFA_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PVFL_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PVFI_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PDYNA_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PDYNL_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PDYNI_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PHRSW_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PHRLW_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PVERVEL_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PAP_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PAPH_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PLSM_d(:, :)
    LOGICAL, ALLOCATABLE, DEVICE :: LDCUM_d(:, :)
    INTEGER(KIND=JPIM), ALLOCATABLE, DEVICE :: KTYPE_d(:, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PLU_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PLUDE_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PSNDE_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PMFU_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PMFD_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PA_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PCLV_d(:, :, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PSUPSAT_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PLCRIT_AER_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PICRIT_AER_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PRE_ICE_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PCCN_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PNICE_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PCOVPTOT_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PRAINFRAC_TOPRFZ_d(:, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQLF_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQIF_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFCQNNG_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFCQLNG_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQRF_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQSF_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFCQRNG_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFCQSNG_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQLTUR_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFSQITUR_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFPLSL_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFPLSN_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFHPSL_d(:, :, :)
    REAL(KIND=JPRB), ALLOCATABLE, DEVICE :: PFHPSN_d(:, :, :)
    TYPE(DIM3) :: GRIDDIM, BLOCKDIM
    
    ! Device array allocation
    ALLOCATE (PT_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PQ_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (BUFFER_TMP_d(NPROMA, NLEV, 3 + NCLV, NGPBLKS))
    ALLOCATE (BUFFER_LOC_d(NPROMA, NLEV, 3 + NCLV, NGPBLKS))
    ALLOCATE (PVFA_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PVFL_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PVFI_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PDYNA_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PDYNL_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PDYNI_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PHRSW_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PHRLW_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PVERVEL_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PAP_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PAPH_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PLSM_d(NPROMA, NGPBLKS))
    ALLOCATE (LDCUM_d(NPROMA, NGPBLKS))
    ALLOCATE (KTYPE_d(NPROMA, NGPBLKS))
    ALLOCATE (PLU_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PLUDE_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PSNDE_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PMFU_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PMFD_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PA_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PCLV_d(NPROMA, NLEV, NCLV, NGPBLKS))
    ALLOCATE (PSUPSAT_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PLCRIT_AER_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PICRIT_AER_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PRE_ICE_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PCCN_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PNICE_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PCOVPTOT_d(NPROMA, NLEV, NGPBLKS))
    ALLOCATE (PRAINFRAC_TOPRFZ_d(NPROMA, NGPBLKS))
    ALLOCATE (PFSQLF_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFSQIF_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFCQNNG_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFCQLNG_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFSQRF_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFSQSF_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFCQRNG_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFCQSNG_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFSQLTUR_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFSQITUR_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFPLSL_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFPLSN_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFHPSL_d(NPROMA, NLEV + 1, NGPBLKS))
    ALLOCATE (PFHPSN_d(NPROMA, NLEV + 1, NGPBLKS))
   
    ! Global timer for the parallel region
    CALL TIMER%START(NUMOMP)

    ! Copy host to device
    PT_d = PT
    PQ_d = PQ
    BUFFER_TMP_d = BUFFER_TMP
    BUFFER_LOC_d = BUFFER_LOC
    PVFA_d = PVFA
    PVFL_d = PVFL
    PVFI_d = PVFI
    PDYNA_d = PDYNA
    PDYNL_d = PDYNL
    PDYNI_d = PDYNI
    PHRSW_d = PHRSW
    PHRLW_d = PHRLW
    PVERVEL_d = PVERVEL
    PAP_d = PAP
    PAPH_d = PAPH
    PLSM_d = PLSM
    LDCUM_d = LDCUM
    KTYPE_d = KTYPE
    PLU_d = PLU
    PLUDE_d = PLUDE
    PSNDE_d = PSNDE
    PMFU_d = PMFU
    PMFD_d = PMFD
    PA_d = PA
    PCLV_d = PCLV
    PSUPSAT_d = PSUPSAT
    PLCRIT_AER_d = PLCRIT_AER
    PICRIT_AER_d = PICRIT_AER
    PRE_ICE_d = PRE_ICE
    PCCN_d = PCCN
    PNICE_d = PNICE
    PCOVPTOT_d = PCOVPTOT
    PRAINFRAC_TOPRFZ_d = PRAINFRAC_TOPRFZ
    PFSQLF_d = PFSQLF
    PFSQIF_d = PFSQIF
    PFCQNNG_d = PFCQNNG
    PFCQLNG_d = PFCQLNG
    PFSQRF_d = PFSQRF
    PFSQSF_d = PFSQSF
    PFCQRNG_d = PFCQRNG
    PFCQSNG_d = PFCQSNG
    PFSQLTUR_d = PFSQLTUR
    PFSQITUR_d = PFSQITUR
    PFPLSL_d = PFPLSL
    PFPLSN_d = PFPLSN
    PFHPSL_d = PFHPSL
    PFHPSN_d = PFHPSN
    YRECLDP_d = YRECLDP
    
    !@cuf CALL YOMCST_UPDATE_DEVICE()
    !@cuf CALL YOETHF_UPDATE_DEVICE()
    
    IF (irank == 0) THEN
 1003 FORMAT(5X, 'NUMPROC=', I0, ', NUMOMP=', I0, ', NGPTOTG=', I0, ', NPROMA=', I0, ', NGPBLKS=', I0)
      WRITE(0, 1003) NUMPROC, NUMOMP, NGPTOTG, NPROMA, NGPBLKS
    END IF
    
    ! Local timer for each thread
    TID = GET_THREAD_NUM()
    CALL TIMER%THREAD_START(TID)
    
    BLOCKDIM = DIM3(NPROMA, 1, 1)
    GRIDDIM = DIM3(1, 1, CEILING(REAL(NGPTOT) / REAL(NPROMA)))
    IBL = (JKGLO - 1) / NPROMA + 1
    ICEND = MIN(NPROMA, NGPTOT - JKGLO + 1)
    
    CALL CLOUDSC_SCC_CUF_K_CACHING<<<GRIDDIM,BLOCKDIM>>>(1, ICEND, NPROMA, NLEV, PTSPHY, PT_d, PQ_d, BUFFER_TMP_d, BUFFER_LOC_d, PVFA_d,  &
    & PVFL_d, PVFI_d, PDYNA_d, PDYNL_d, PDYNI_d, PHRSW_d, PHRLW_d, PVERVEL_d, PAP_d, PAPH_d, PLSM_d, LDCUM_d, KTYPE_d, PLU_d,  &
    & PLUDE_d, PSNDE_d, PMFU_d, PMFD_d, PA_d, PCLV_d, PSUPSAT_d, PLCRIT_AER_d, PICRIT_AER_d, PRE_ICE_d, PCCN_d, PNICE_d,  &
    & PCOVPTOT_d, PRAINFRAC_TOPRFZ_d, PFSQLF_d, PFSQIF_d, PFCQNNG_d, PFCQLNG_d, PFSQRF_d, PFSQSF_d, PFCQRNG_d, PFCQSNG_d,  &
    & PFSQLTUR_d, PFSQITUR_d, PFPLSL_d, PFPLSN_d, PFHPSL_d, PFHPSN_d, YRECLDP_d, NGPBLKS)
    istat = cudaDeviceSynchronize()
    
    
    CALL TIMER%THREAD_END(TID)
    ! Copy device to host
    BUFFER_TMP = BUFFER_TMP_d
    BUFFER_LOC = BUFFER_LOC_d
    PLUDE = PLUDE_d
    PCOVPTOT = PCOVPTOT_d
    PRAINFRAC_TOPRFZ = PRAINFRAC_TOPRFZ_d
    PFSQLF = PFSQLF_d
    PFSQIF = PFSQIF_d
    PFCQNNG = PFCQNNG_d
    PFCQLNG = PFCQLNG_d
    PFSQRF = PFSQRF_d
    PFSQSF = PFSQSF_d
    PFCQRNG = PFCQRNG_d
    PFCQSNG = PFCQSNG_d
    PFSQLTUR = PFSQLTUR_d
    PFSQITUR = PFSQITUR_d
    PFPLSL = PFPLSL_d
    PFPLSN = PFPLSN_d
    PFHPSL = PFHPSL_d
    PFHPSN = PFHPSN_d
    
    
    CALL TIMER%END()
    
    ! On GPUs, adding block-level column totals is cumbersome and
    ! error prone, and of little value due to the large number of
    ! processing "thread teams". Instead we register the total here.
    CALL TIMER%THREAD_LOG(TID=TID, IGPC=NGPTOT)
    
    CALL TIMER%PRINT_PERFORMANCE(NPROMA, NGPBLKS, NGPTOT)
    
    ! De-allocation
    DEALLOCATE (PT_d)
    DEALLOCATE (PQ_d)
    DEALLOCATE (BUFFER_TMP_d)
    DEALLOCATE (BUFFER_LOC_d)
    DEALLOCATE (PVFA_d)
    DEALLOCATE (PVFL_d)
    DEALLOCATE (PVFI_d)
    DEALLOCATE (PDYNA_d)
    DEALLOCATE (PDYNL_d)
    DEALLOCATE (PDYNI_d)
    DEALLOCATE (PHRSW_d)
    DEALLOCATE (PHRLW_d)
    DEALLOCATE (PVERVEL_d)
    DEALLOCATE (PAP_d)
    DEALLOCATE (PAPH_d)
    DEALLOCATE (PLSM_d)
    DEALLOCATE (LDCUM_d)
    DEALLOCATE (KTYPE_d)
    DEALLOCATE (PLU_d)
    DEALLOCATE (PLUDE_d)
    DEALLOCATE (PSNDE_d)
    DEALLOCATE (PMFU_d)
    DEALLOCATE (PMFD_d)
    DEALLOCATE (PA_d)
    DEALLOCATE (PCLV_d)
    DEALLOCATE (PSUPSAT_d)
    DEALLOCATE (PLCRIT_AER_d)
    DEALLOCATE (PICRIT_AER_d)
    DEALLOCATE (PRE_ICE_d)
    DEALLOCATE (PCCN_d)
    DEALLOCATE (PNICE_d)
    DEALLOCATE (PCOVPTOT_d)
    DEALLOCATE (PRAINFRAC_TOPRFZ_d)
    DEALLOCATE (PFSQLF_d)
    DEALLOCATE (PFSQIF_d)
    DEALLOCATE (PFCQNNG_d)
    DEALLOCATE (PFCQLNG_d)
    DEALLOCATE (PFSQRF_d)
    DEALLOCATE (PFSQSF_d)
    DEALLOCATE (PFCQRNG_d)
    DEALLOCATE (PFCQSNG_d)
    DEALLOCATE (PFSQLTUR_d)
    DEALLOCATE (PFSQITUR_d)
    DEALLOCATE (PFPLSL_d)
    DEALLOCATE (PFPLSN_d)
    DEALLOCATE (PFHPSL_d)
    DEALLOCATE (PFHPSN_d)
  
  END SUBROUTINE CLOUDSC_DRIVER_GPU_SCC_CUF_K_CACHING
  
END MODULE CLOUDSC_DRIVER_GPU_SCC_CUF_K_CACHING_MOD
