PROGRAM DWARF_CLOUDSC_CLAW

USE PARKIND1, ONLY: JPIM
USE CLOUDSC_GLOBAL_STATE_MOD, ONLY: CLOUDSC_GLOBAL_STATE
USE CLOUDSC_DRIVER_GPU_CLAW_MOD, ONLY: CLOUDSC_DRIVER_GPU_CLAW

IMPLICIT NONE

CHARACTER(LEN=20) :: CLARG
INTEGER(KIND=JPIM) :: IARGS, LENARG, JARG, I

INTEGER(KIND=JPIM) :: NUMOMP  = 1     ! Number of OpenMP threads for this run
INTEGER(KIND=JPIM) :: NGPTOT  = 16384 ! Number of grid points (as read from command line)
INTEGER(KIND=JPIM) :: NPROMA  = 16384 ! NPROMA blocking factor (currently active)

TYPE(CLOUDSC_GLOBAL_STATE) :: GLOBAL_STATE

#include "abor1.intfb.h"

IARGS = COMMAND_ARGUMENT_COUNT()

! Get the number of OpenMP threads to use for the benchmark
if (IARGS >= 1) then
   CALL GET_COMMAND_ARGUMENT(1, CLARG, LENARG)
   READ(CLARG(1:LENARG),*) NUMOMP
end if

! Get total number of grid points (NGPTOT) with which to run the benchmark
IF (IARGS >= 2) THEN
  CALL GET_COMMAND_ARGUMENT(2, CLARG, LENARG)
  READ(CLARG(1:LENARG),*) NGPTOT
END IF

! Get the block size (NPROMA) for which to run the benchmark  
IF (IARGS >= 3) THEN
  CALL GET_COMMAND_ARGUMENT(3, CLARG, LENARG)
  READ(CLARG(1:LENARG),*) NPROMA
ENDIF

IF (MODULO(NPROMA, 64) /= 0) THEN
  CALL ABOR1('ERROR: CLAW kernel requires NPROMA to be a multiple of 64.')
END IF

! Create a global global memory state from serialized input data
CALL GLOBAL_STATE%LOAD(NPROMA, NGPTOT)

! Call the driver to perform the parallel loop over our kernel
CALL CLOUDSC_DRIVER_GPU_CLAW(NUMOMP, NPROMA, GLOBAL_STATE%KLEV, NGPTOT, &
     & GLOBAL_STATE%KFLDX, GLOBAL_STATE%PTSPHY, &
     & GLOBAL_STATE%PT, GLOBAL_STATE%PQ, &
     & GLOBAL_STATE%TENDENCY_CML, GLOBAL_STATE%TENDENCY_TMP, GLOBAL_STATE%TENDENCY_LOC, &
     & GLOBAL_STATE%B_CML,   GLOBAL_STATE%B_TMP, GLOBAL_STATE%B_LOC, &
     & GLOBAL_STATE%PVFA,    GLOBAL_STATE%PVFL,  GLOBAL_STATE%PVFI, &
     & GLOBAL_STATE%PDYNA,   GLOBAL_STATE%PDYNL, GLOBAL_STATE%PDYNI, &
     & GLOBAL_STATE%PHRSW,   GLOBAL_STATE%PHRLW, &
     & GLOBAL_STATE%PVERVEL, GLOBAL_STATE%PAP,   GLOBAL_STATE%PAPH, &
     & GLOBAL_STATE%PLSM,    GLOBAL_STATE%LDCUM, GLOBAL_STATE%KTYPE, &
     & GLOBAL_STATE%PLU,     GLOBAL_STATE%PLUDE, GLOBAL_STATE%PSNDE, &
     & GLOBAL_STATE%PMFU,    GLOBAL_STATE%PMFD, &
     & GLOBAL_STATE%LDSLPHY, GLOBAL_STATE%LDMAINCALL, GLOBAL_STATE%PA, &
     & GLOBAL_STATE%PCLV,    GLOBAL_STATE%PSUPSAT,&
     & GLOBAL_STATE%PLCRIT_AER, GLOBAL_STATE%PICRIT_AER, GLOBAL_STATE%PRE_ICE, &
     & GLOBAL_STATE%PCCN,     GLOBAL_STATE%PNICE,&
     & GLOBAL_STATE%PCOVPTOT, GLOBAL_STATE%PRAINFRAC_TOPRFZ, &
     & GLOBAL_STATE%PFSQLF,   GLOBAL_STATE%PFSQIF ,  GLOBAL_STATE%PFCQNNG,  GLOBAL_STATE%PFCQLNG, &
     & GLOBAL_STATE%PFSQRF,   GLOBAL_STATE%PFSQSF ,  GLOBAL_STATE%PFCQRNG,  GLOBAL_STATE%PFCQSNG, &
     & GLOBAL_STATE%PFSQLTUR, GLOBAL_STATE%PFSQITUR, &
     & GLOBAL_STATE%PFPLSL,   GLOBAL_STATE%PFPLSN,   GLOBAL_STATE%PFHPSL,   GLOBAL_STATE%PFHPSN, &
     & GLOBAL_STATE%PEXTRA    )

! Validate the output against serialized reference data
CALL GLOBAL_STATE%VALIDATE(NPROMA, NGPTOT)

END PROGRAM DWARF_CLOUDSC_CLAW
