MODULE CLOUDSC_GLOBAL_STATE_MOD
  ! Driver module to manage the setup and teardown of the dwarf memory state
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMPHYDER, ONLY: STATE_TYPE
  USE YOECLDP, ONLY: NCLV
  USE LOAD_STATE_MOD, ONLY: QUERY_DIMENSIONS, LOAD_AND_EXPAND

  IMPLICIT NONE

  TYPE CLOUDSC_GLOBAL_STATE
    ! Memory state containing raw fields annd tendencies for CLOUDSC dwarf
    !
    ! Note that the global state has an additional outermost block
    ! dimension allocated for each field variable.
    INTEGER(KIND=JPIM)                   :: NPROMA, KLEV    ! Grid points and vertical levels per block
    INTEGER(KIND=JPIM)                   :: NGPTOT, NBLOCKS ! Total number of grid points and blocks
    INTEGER(KIND=JPIM)                   :: KFLDX 
    LOGICAL                              :: LDSLPHY 
    LOGICAL                              :: LDMAINCALL      ! T if main call to cloudsc
    REAL(KIND=JPRB)                      :: PTSPHY          ! Physics timestep

    ! Input field variables and tendencies
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLCRIT_AER(:,:,:) 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PICRIT_AER(:,:,:) 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PRE_ICE(:,:,:) 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCCN(:,:,:)     ! liquid cloud condensation nuclei
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PNICE(:,:,:)    ! ice number concentration (cf. CCN)

    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PT(:,:,:)       ! T at start of callpar
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PQ(:,:,:)       ! Q at start of callpar
    TYPE(STATE_TYPE)                     :: TENDENCY_CML    ! cumulative tendency used for final output
    TYPE(STATE_TYPE)                     :: TENDENCY_TMP    ! cumulative tendency used as input
    TYPE(STATE_TYPE)                     :: TENDENCY_LOC    ! local tendency from cloud scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFA(:,:,:)     ! CC from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFL(:,:,:)     ! Liq from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVFI(:,:,:)     ! Ice from VDF scheme
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNA(:,:,:)    ! CC from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNL(:,:,:)    ! Liq from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDYNI(:,:,:)    ! Liq from Dynamics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHRSW(:,:,:)    ! Short-wave heating rate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHRLW(:,:,:)    ! Long-wave heating rate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PVERVEL(:,:,:)  ! Vertical velocity
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAP(:,:,:)      ! Pressure on full levels
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAPH(:,:,:)     ! Pressure on half levels
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLSM(:,:)       ! Land fraction (0-1) 
    LOGICAL,         POINTER, CONTIGUOUS :: LDCUM(:,:)      ! Convection active
    INTEGER(KIND=JPIM),POINTER,CONTIGUOUS:: KTYPE(:,:)      ! Convection type 0,1,2
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLU(:,:,:)      ! Conv. condensate
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PLUDE(:,:,:)    ! Conv. detrained water 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSNDE(:,:,:)    ! Conv. detrained snow
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PMFU(:,:,:)     ! Conv. mass flux up
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PMFD(:,:,:)     ! Conv. mass flux down
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PA(:,:,:)       ! Original Cloud fraction (t)
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PEXTRA(:,:,:,:) ! extra fields
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLV(:,:,:,:) 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSUPSAT(:,:,:)

    ! Output fields used for validation
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCOVPTOT(:,:,:) ! Precip fraction
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PRAINFRAC_TOPRFZ(:,:) 
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQLF(:,:,:)   ! Flux of liquid
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQIF(:,:,:)   ! Flux of ice
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFCQLNG(:,:,:)  ! -ve corr for liq
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFCQNNG(:,:,:)  ! -ve corr for ice
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQRF(:,:,:)   ! Flux diagnostics
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQSF(:,:,:)   ! for DDH, generic
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFCQRNG(:,:,:)  ! rain
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFCQSNG(:,:,:)  ! snow
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQLTUR(:,:,:) ! liquid flux due to VDF
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFSQITUR(:,:,:) ! ice flux due to VDF
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFPLSL(:,:,:)   ! liq+rain sedim flux
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFPLSN(:,:,:)   ! ice+snow sedim flux
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFHPSL(:,:,:)   ! Enthalpy flux for liq
    REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFHPSN(:,:,:)   ! Enthalp flux for ice

  CONTAINS
    PROCEDURE :: LOAD => CLOUDSC_GLOBAL_STATE_LOAD
  END TYPE CLOUDSC_GLOBAL_STATE

CONTAINS

  SUBROUTINE CLOUDSC_EXECUTE_KERNEL()
    ! Execute the benchmark by calling the CLOUDSC kernel
    ! with an outer-parallel block loop (NPROMA).

  END SUBROUTINE CLOUDSC_EXECUTE_KERNEL


  SUBROUTINE CLOUDSC_GLOBAL_STATE_LOAD(THIS, NPROMA, NGPTOT)
    ! Load reference input data via serialbox
    CLASS(CLOUDSC_GLOBAL_STATE) :: THIS
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPTOT

    INTEGER(KIND=JPIM) :: KLON, NBLOCKS

    NBLOCKS = (NGPTOT / NPROMA) + MIN(MOD(NGPTOT,NPROMA), 1)
    CALL QUERY_DIMENSIONS(KLON, THIS%KLEV, THIS%KFLDX)

    CALL LOAD_AND_EXPAND('PLCRIT_AER', THIS%PLCRIT_AER, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PICRIT_AER', THIS%PICRIT_AER, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PRE_ICE', THIS%PRE_ICE, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PCCN', THIS%PCCN, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PNICE', THIS%PNICE, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PT', THIS%PT, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PQ', THIS%PQ, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('TENDENCY_CML', THIS%TENDENCY_CML, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('TENDENCY_TMP', THIS%TENDENCY_TMP, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PVFA', THIS%PVFA, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PVFL', THIS%PVFL, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PVFI', THIS%PVFI, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PDYNA', THIS%PDYNA, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PDYNL', THIS%PDYNL, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PDYNI', THIS%PDYNI, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PHRSW', THIS%PHRSW, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PHRLW', THIS%PHRLW, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PVERVEL', THIS%PVERVEL, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PAP', THIS%PAP, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PAPH', THIS%PAPH, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PLSM', THIS%PLSM, KLON, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('LDCUM', THIS%LDCUM, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('KTYPE', THIS%KTYPE, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PLU', THIS%PLU, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PLUDE', THIS%PLUDE, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PSNDE', THIS%PSNDE, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PMFU', THIS%PMFU, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PMFD', THIS%PMFD, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PA', THIS%PA, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! Note: The 0-sized array (KFLDX=0) seems to create problems when filled with
    ! data from the C-backend, causing memory corruption if enabled.
    ! CALL LOAD_AND_EXPAND('PEXTRA', THIS%PEXTRA, KLON, THIS%KLEV, THIS%KFLDX, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PCLV', THIS%PCLV, KLON, THIS%KLEV, NCLV, NPROMA, NGPTOT, NBLOCKS)
    CALL LOAD_AND_EXPAND('PSUPSAT', THIS%PSUPSAT, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PRAINFRAC_TOPRFZ', THIS%PRAINFRAC_TOPRFZ, KLON, THIS%KLEV, NPROMA, &
    !      & NGPTOT, NBLOCKS)

    ! Output fields are simply allocated and zero'd
    ! CALL LOAD_AND_EXPAND('PCOVPTOT', THIS%PCOVPTOT, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('TENDENCY_LOC', THIS%TENDENCY_LOC, KLON, THIS%KLEV, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQLF', THIS%PFSQLF, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQIF', THIS%PFSQIF, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFCQLNG', THIS%PFCQLNG, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFCQNNG', THIS%PFCQNNG, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQRF', THIS%PFSQRF, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQSF', THIS%PFSQSF, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFCQRNG', THIS%PFCQRNG, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFCQSNG', THIS%PFCQSNG, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQLTUR', THIS%PFSQLTUR, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFSQITUR', THIS%PFSQITUR, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFPLSL', THIS%PFPLSL, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFPLSN', THIS%PFPLSN, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFHPSL', THIS%PFHPSL, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)
    ! CALL LOAD_AND_EXPAND('PFHPSN', THIS%PFHPSN, KLON, THIS%KLEV+1, NPROMA, NGPTOT, NBLOCKS)

  END SUBROUTINE CLOUDSC_GLOBAL_STATE_LOAD

  SUBROUTINE CLOUDSC_GLOBAL_STATE_VALIDATE()
    ! Validate the correctness of output against reference data

  END SUBROUTINE CLOUDSC_GLOBAL_STATE_VALIDATE

END MODULE CLOUDSC_GLOBAL_STATE_MOD
