INTERFACE
SUBROUTINE DOTPROD3(PGP1,PGP2,PPROD)
USE PARKIND1 ,ONLY : JPIM, JPRB
REAL(KIND=JPRB),INTENT(IN) :: PGP1(:,:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP2(:,:,:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PPROD
END SUBROUTINE DOTPROD3
END INTERFACE
